### ISSUE TITLE
library attendence data

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#100]
Do we have data for the[ library attended](https://github.com/jiscdev/xapi/blob/ds10-recipedev/recipes/visited-library.md) draft recipes?

**Comment by arc12** [comment]
Query: what makes library attendance special? What about computer suites, or workshop facilities?
Could this be re-cast as accessing an open-access physical study resource?




(btw the draft recipe includes the words "reading list")

**Comment by alleycat58uk** [comment]
Ignoring for the 'reading list' issue, in terms of data, the thing that makes library attendance is many libraries have turnstyle systems such as [Sentry](http://www.hardwarespecialties.com/retail-store-fixtures/security-turnstiles/).  This means they record the time a user enters and leaves the Library which in turn allows the duration of visit to be calculated.  Other areas tend to use swipe card or keypad door access which is inacurate due to tailgating.

Does this scenario fit with login/logout?
