### ISSUE TITLE
presence recipe. Do we want need a 'leaving' recipe

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#118]
@alleycat58uk Do you have a wifi disconnect in the logs? Could we have a separate recipe for leaving the area?

**Comment by alleycat58uk** [comment]
I have been told there is an association and disassociation event logged but I haven't seen the logs yet.  We are due to test the Syslog server capture on Monday so I can let you know then.

If it is there then maybe we should capture it too.  Could that be an extension to the verb to say when the 'presence' started and ended?

**Comment by ds10** [comment]
@alleycat58uk  We could think about capture of  association and disassociation  in  one recipe. I guess we would have to think about some of the issues differently then. Do you want to chat next week after you've seen the logs? My Skype is ds10 if  you want to chat.

**Comment by ds10** [comment]
From Monday call:

If any presence recipes have leaving then yes, we want a separate recipe

**Comment by ds10** [comment]
really a part of #109 now. (But @alleycat58uk data does not have leaving information yet.)
