### ISSUE TITLE
Presence recipe: area present

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#120]
From call - Do we need to develop a way to associate a mac address with area of university? 

 Create a place for an identifier for discussion.

**Comment by alleycat58uk** [comment]
To put this in context, we have over 700 APs at UoG.  Buildings are on multilevels with APs generally located on the ceilings.  This means the "area" is within a 3d space and often APs overlap.  Given the location accuracy of this technology maybe an extra field on the Object to give a texual location reference would suffice?  Or is that something implied (and therefore linked) by the mac address of the AP?

**Comment by arc12** [comment]
@alleycat58uk - from a data analysis and sense-making perspective, I think it would be useful to know "area" at a fairly coarse level. For example, for data mining, I would expect to get further if I could condense a dozen or so APs into "student was probably in the study area", "... in the engineering dept", "... in halls", "... in building B" etc. My hunch is that there will be some areas which are more significant for analytics, although the pattern is probably quite complex.

We could look at this empirically, and use clustering to group the AP MAC addrs into zones based on patterns of activity, but this might get us nowhere fast!

This is a bit of R&D, both for what is feasible in the data acquisition and in downstream analytical utility.

Adam

**Comment by alleycat58uk** [comment]
If we are going to group into areas then the first "fairly coarse level" suggestion you mentioed makes sense.  We would probably want to define areas such as library, efectory, media centre etc.  We would also potentially be interested in presence at a given campus as we are split over 4 sites.  For instance, looking at where the student lives, at which campus the course is taught and which campus they appear on the network the most could be interesting.

**Comment by wilmTap** [comment]
Wondering whether we should introduce resolution entities beyond xAPI for these. That is: use the xAPI statements to transport the raw data to the LRW (as they are designed to do), but have entities in the LRW that aggregate ranges of raw data points in more useable chunks. 

That would allow us to use human generated clusters before there is enough data to make machine generated clusters, and it'd also allow us to have multiple clusterings for different purposes. Finally, it might future proof the xAPI data, because it'll separate the raw data from our assumptions and changing goals.

**Comment by ds10** [comment]
From Monday call

- Update the documentation/recipe to say that institutions need a chat with a data scientist about the areas they use
