### ISSUE TITLE
Access to Panopto (online lecture) capture material via VLE logs/ xapi?

### ISSUE THREAD

**Issue by robwynj** [jiscdev/xapi#124]
Out of interest -

Can we pickup activities around access of VLE embedded panopto (online lecture) captured material at all in future via our xAPI plugins/ recipes?

Kind Regards

Rob

**Comment by ds10** [comment]
I think It depends what we want from this,  the viewed recipe can be used if you just want to capture the fact a browser made a request material. Otherwise we need to know what data is collected about Panopto, what we want and what sort of recipe that fits under

**Comment by arc12** [comment]
There is an active xAPI Community of Practice for video playback. I used to contribute to this (and wrote a review of playback events with mapping to xAPI)
https://groups.google.com/a/adlnet.gov/forum/#!forum/xapi-profile-cop
http://www.laceproject.eu/publications/public-drafts/wp7-video.pdf

I think lecture capture playback is a special case of video.

Adam

**Comment by ds10** [comment]
From cetis call for monday call:

Are we going ahead with video playback videos?

**Comment by ds10** [comment]
- yes follow up Adams link and ims caliper(? )profile

**Comment by alanepaull** [comment]
Additional from Monday 5 Dec call:

Data on this may be available from Edge Hill, so we can review the type of information held.

**Comment by ds10** [comment]
work on this has been been contribution with adl at lak etc. See the video profile at http://xapi.vocab.pub/video.html

**Comment by ds10** [comment]
From 5th Feb call:

@camwestwood has additional information for this, will review  with @gmoger-jisc and pass on information

**Comment by robwynj** [comment]
Keen to also pull-in Echo360 data/ feeds, as part of this piece.

Kind Regards

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG Prince2 & Agile Certified Practitioner

Director of Data Analytics – Jisc
Cyfarwyddwr Data Dadansoddiadau - Jisc

email & skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by camwestwood** [comment]
Valid point Rob; I think the aim for most of these is to make them platform agnostic but looking into Echo360 as well may give us more of a steer on what sort of data we can pull through from both systems. I'll consider this when providing further details

**Comment by robwynj** [comment]
Spot-on, exactly what I was getting at – they are the 2 big players in this market, I believe.

Kind Regards

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG Prince2 & Agile Certified Practitioner

Director of Data Analytics – Jisc
Cyfarwyddwr Data Dadansoddiadau - Jisc

email & skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by ds10** [comment]
data model for the xAPI video cop: https://liveaspankaj.gitbooks.io/xapi-video-profile/content/statement_data_model.html

**Comment by camwestwood** [comment]
**Panopto/Echo360 online lectures viewed xAPI recipe**

For further information on online lecture viewed.

I would think that this data would form one recipe for ‘viewed’. I have put together the fields that I feel would be useful to draw from both systems, they seem to hold very similarly structured data.

- Session_ID
- Timestamp
- Viewer (User_ID)
- User Email
- Content
- Viewing type
- Views
- Minutes watched/delivered 

Please let me know if you need any more information to start having a look into this.

Best wishes, 
Cam

**Comment by ds10** [comment]
I guess the questions here are about the level of detail we want, and if we decide 'not that much detail', then how do we design this so that we don't make things difficult down the road if we decide we want more:.

The verb we used in the viewed statements is: 

<table>
<tr><th align="left">Verb</th><td>Viewed</td></tr>
<tr><th align="left">Description</th><td>Indicates that the Actor has viewed the Object.</td></tr>
<tr><th align="left">IRI</th><td> <a href="http://id.tincanapi.com/verb/viewed"> http://id.tincanapi.com/verb/viewed</a> </td></tr>
<tr><th align="left">Statement Example</th><td> <a href="/recipes/vle/Module-View.md#verb">Resource Viewed</a> </td></tr>
</table>

That doesn't tell us much about what happened to the actual video, was it viewed, paused etc? [The xapi video profile](https://liveaspankaj.gitbooks.io/xapi-video-profile/content/statement_data_model.html), doesn't have a viewed verb in its statement template, it has a bunch of things that can be done to the video (Initialized, paused, played etc).

I think we need input from analysts people who know the data etc (
@arc12 @camwestwood @alanepaull @gmoger-jisc ? ):

- Does keeping it in line with our current viewed statements make it easier from an analyst point of view, because you may want to pull out a bunch of viewed statements across recipes and it is better to query for one verb? Or does it not matter?
- Or.. is it better trying to align ourselves with mandatory verbs in something like the xapi video profile spec, so that we can flesh out in more what the user does with the video.
- Or.. If we use an overarching viewed statement, but then decide to use a breakdown of statements of video interactions AS WELL, would this be really confusing from an analysists pov.

(Do panopto and echo 360 give us the information needed to use a break this down into multiple statements regarding student interactions with video)

**Comment by camwestwood** [comment]
A very valid point there David; I personally don't think that it would matter for analysis purposes to pull across different types of viewed under one recipe, I would consider this a separate 'stream' of data; I'm just trying to picture the new recipe in the context of watching a video (maybe watched/played would be a better verb, played being part of the current xAPI video profile, I think this would make sense), I don't think that the systems in question hold as much detail as whether a video was paused or anything and from our perspective, that level of granularity feels like overkill, I think that the views (plays/watches and minutes watched) is plenty of detail. The systems can provide more detail on where the user watches the video from (but again, I don't think we are interested in that level of detail - it could be brought in as metadata

Let me know your thoughts :)

**Comment by arc12** [comment]
my 10p

Potentially both levels of detail!

A realistic point of view is that "not all systems will be able to provide detail", and I think we will always want to allow for lowest-common-denominator processing. i.e I am a +1 for a simple statement which indicates the student accessed the lecture-cap. I dont have a view about whether this is "view" or "access" semantics. I DO think the spec should be clear that where a recording is subject to a play, stop. start, replay, fast-forward... session, then that is ONE event in this LCD model.

I would favour a model which clearly discriminates lecture cap viewing from other videos, where this is possible. I guess this depends where the logging occurs: in panopto (etc) or in a host vle or content player.

There surely is also value in being able to understand how videos are being used, both for student-level analytics and curriculum analytics. So... detail is desirable.

**Comment by robwynj** [comment]
I agree, both is required. Does the same type of question as this, exist for xAPI LA intervention recipes too?

Kind Regards

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG Prince2 & Agile Certified Practitioner

Director of Data Analytics – Jisc
Cyfarwyddwr Data Dadansoddiadau - Jisc

email & skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by ds10** [comment]
So, the census is swaying towards

`* Or.. If we use an overarching viewed statement, but then decide to use a breakdown of statements of video interactions AS WELL, would this be really confusing from an analysists pov.`

I'll knock something up using viewed for us to talk about at next meeting, and we can talk around how these fit in with more detailed statements.

@robwynj The intervention statements where something we knocked up quickly with Micheal to support development of a jisc system (I'm sure it wasn't study goal - micheal demoed it?), but afaik they didn't get kicked around much. I think we went down the route of having something high level. Create, close and update cases or attach a note to these cases. 

I don't know if these have been implemented in the jisc system, and I don't know what kind of data we get out of institutional systems. But open a case, close a case add a note is kind of generic functionality?

**Comment by robwynj** [comment]
Hi David,

Interesting – I suppose I was going down the route of intervention “taken place” or having been held (in the past) – again, a summary statement / statement of fact, which would be useful if importing historical data regards interventions (so no granularity here – except I suppose you could do a create and close entry pair for this purpose on the same date/ time stamp – do you see what I am getting at!)

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG Prince2 & Agile Certified Practitioner

Director of Data Analytics – Jisc
Cyfarwyddwr Data Dadansoddiadau - Jisc

email & skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by camwestwood** [comment]
Brill, thanks for the input guys, yeah that sounds good to me David. I think that the granularity of data that we can pull will further come to light when we're working more directly with the systems and know more specifically what we can pull out, but with what I have now, it looks like they mostly tend to record time watched at a higher level. 

I think that the first step is a viewed statement (if we can capture more data breaking down interactions, that's great and no doubt of further use), for me I'm just exploring the more high level interactions with lectures for activity data at the moment; with the 2 systems that we are looking at now, I think that minutes watched is the main interest; I'm just not sure that it would be of use for this specific strand of work to know that a student paused the playback etc. I'm happy to discuss further is others have any thoughts on this

**Comment by ds10** [comment]
OK - I am on this but in the mean time it might be worth looking at the viewed generic recipe? https://github.com/jiscdev/xapi/blob/1.0.3/generic/view.md

There are some addition properties we may want, for example a result entity (or additional context extensions?) with minutes watched.

There are also bits in the common structures that might be worth looking at, that you haven’t currently talked about, do we have course information for example?


Thinking aloud confusing bit:
Perhaps it might be worth a chat - I always think that the process and structure of the repository may be a bit off-putting/confusing. Within each recipe we have statements, and in those statements we have common structures that can be used across statements. I think this is a good approach because it means there is consistency across statements, and helps us think about things we may want to capture in each statement.

But.. on the flip side to this we also host the JSON template and the TSV definitions which are practical things that jisc use to ask for data and turn it into JSON. It probably is good to have them in the same place, but describing both the things jisc ask for from the host systems and what is actually allowed in the spec differ together is a bit confusing. I often think ‘what should be in the examples within the descriptive markdown of the statement’ should it be everything that is allowed by the spec, or everything that jisc will receive from most institutions? Maybe we just need better sign posting

**Comment by ds10** [comment]
added a first stab on 1.0.3 and links on readme.

Sugguest we takle this and #292 on the 18th

**Comment by alanepaull** [comment]
Looking at vidio-viewed.md: 
Result - do we need the new-minted extension 'https://jisc.ac.uk/minutes-watched'? The video profile (https://liveaspankaj.gitbooks.io/xapi-video-profile/content/statement_data_model.html) has result.duration, described as "total time spent consuming the video". So, this could be an ISO 8601 duration in minutes; for example, 'PT12M' for 12 minutes, or hours, minutes and seconds for greater accuracy, 'PT1H12M34.5S'. This might be more interoperable and more flexible.

**Comment by ds10** [comment]
Notes from call:

* Activity types
- have video activty type as is
- we can use sub-types: a lecture capture for example
- we have statementcat
- we also have platform

* remove view count

**Comment by ds10** [comment]
For call:

Changes have been made to files according to notes.

Next steps:

- Cam & David to run some fake data through it? - Either Cam can send an example TSV which we can post on the repo, or could try it at Jisc end?
- For the TSV definition file and JSON template I've used variables consistant with what is in the repo. So a call with Cam with would be good?

**Comment by ds10** [comment]
from weekly call:

- Cam to send data to David to run through the JSON templates

**Comment by ds10** [comment]
Example output from @camwestwood data:

```
{
	"version": "1.0.0",
	"timestamp": "11/15/2018 1:44:52 AM",
	"actor": {
		"objectType": "Agent",
		"account": {
			"name": "username",
			"homePage": "**HOMEPAGE**"
		}
	},
	"verb": {
		"id": "http://id.tincanapi.com/verb/viewed",
		"display": {
			"en": "viewed"
		},

	"object": {
		"objectType": "Activity",
		"id": "**HOMEPAGE**/749bab78-5913-44c9-b58e-a8ef01538b2e",
		"definition": {
			"type": "https://w3id.org/xapi/video/activity-type/video"
		}
	},

	"result": {
		"duration": "0.030178967"
    },

	"context": {

		"extensions": {

			"http://xapi.jisc.ac.uk/recipeCat": "Video",
			"http://xapi.jisc.ac.uk/sessionId": "0ecc10b9-b161-4780-a3b9-a99900196b8a",
			"http://xapi.jisc.ac.uk/version": "1.0.3"
		}
	}
}
```

some notes:

- USERNAME or USER_ID, what is the difference? 
- Email: Is in the data, but should it really be in an experience statement?
- Session-id: session ID vs  session_name, what is the difference?
- Folder ID and foldername? What are they? Used ID in iri for object.id
- What is viewing type, where should it go?
- No homepage "URL of the home page of the application for which the login id applies." Is this given seperatly somewhere?
