### ISSUE TITLE
Data for attendance and student goal to cetis

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#137]
On Feb 30th call I think we decided to work on these recipes firsts as data was coming in to jisc for them. Could Cetis get some form of this when it comes in @leebaylis @michaelwebbjisc 

update: it is attendance data, not presence

**Comment by michaelwebbjisc** [comment]
I'll ad more later, but this is the template we are using for the incoming data:

https://docs.google.com/spreadsheets/d/1WDbDTz_qsw4SJXstU71cAidFQGy7wr0vw_IsoormyEI/edit?usp=sharing

it's only got two rows, one showing mandatory minimum and one with more.  I'll more as we get it!

**Comment by arc12** [comment]
This may not be the right place for this but...
Some comments on this sample and also on the google spreadsheet which outlines the field descriptions.

ACTIVITY_EVENT_ID - assumed to be the identifier in a timetabling/scheduling system.
STUDENT_ID - obvious. Forms unique index with ACTIVITY_EVENT_ID

Implications:
- situations like multiple swipes must be flattened to a single attendance
- if replacing a record already in the LRW, voiding statements is required.

STUDENT_ACTIVITY_SEQ_ID - I don't get the purpose of this. What is the use case. Can someone explain. Surely the datetimes give all the sequence info required.

ACTIVITY_TYPE_ID and ACTIVITY_TYPE - I assume the latter is just the nice readable label for the activity type. Although it might be nice to have a standard list for these, I rather doubt that is achievable. The ID should be mandatory but not the label, which should be a "recommended" language map as verb.display is. For UDD-like representation, ACTIVITY_TYPE_ID is a code list. For xAPI, we will need to explain how sites will create URIs for this, or diverge from xAPI orthodoxy.

ACTIVITY_MAX_COUNT - I don't understand why this is there. I think I've also seen more than one explanation of what it means. What is the precise meaning? What is the use case? 

MOD_INSTANCE_ID - obvious. Not required to be part of the uniqueness constraint (PK)

START and END DATETIMES - see another issue. Seem straightforward

ACTIVITY_MANDATORY - seems fine. A boolean to be consistent with xAPI success/completion

ACTIVITY_ATTENDED -seems fine. Boolean again.

ACTIVTY_LATE - propose this should CHANGE to be an attendance code. Some sites/software has a range of codes which might be applied for different lateness or different kinds of absence (authorised/condoned/unauthorised). A simple flag is too crude. Implication is similar to activity type: for xAPI we should probably add a "display" and work out the URI formation rule.

ACTIVITY_LOGGED* - ok...

**Comment by michaelwebbjisc** [comment]
STUDENT_ACTIVITY_SEQ_ID -  I don't think we need this - i think it was related to one institutions data.

ACTIVITY_MAX_COUNT - the maximum number of people that could have attended the event.  Used to find percentage of people attending etc.

ACTIVTY_LATE - agreed.

On all the boolean ones, I think it makes things easier if we follow UDD convention 1=YES 2 =NO, which gives us scope to add other values if needed.  What do you think?

**Comment by arc12** [comment]
re max count - so this is used to avoid fetching and counting all records for an event? i.e. the intention is that this is a convenience data element.

re ACTIVITY_LATE - what I didn;t make clear was that the semantics is no longer about lateness, but a code which gives nuance to a true/false "attended". This was implied but that invites inference, which is our enemy when writing specs! Call this ATTENDANCE_CODE

Re boolean ones.
- mandatory seems clearly binary but I guess we have to deal with cases where the obligation is not known. In such cases, however, I think it would make most sense for the source system to make an educated guess (OK I mean the people writing the data extract script use their local knowledge) at true/false.
- attended is arguably one where "not known" is a real world case which cannot be guessed (without looking at a student's history), e.g. due to recording system failure on day X. I can see two options here: a) send "not known" statements, requiring either omission of the activity_attended component or a third value (hence not boolean); b) do not send "not known" statements and only need a boolean

On the whole, I find using a boolean along with another element which gives detail (aka attendance_code) to be both more consistent with xAPI convention (and otherwise, wouldn't we need to use yes/no URIs rather than "1" or "2") but also cleaner to process. I'm not religeous about this, though... Whatever the encoding, I think it would be helpful to have the semantics as being boolean so the data processing code isn't at the mercy of the addition of other values...

**Comment by ds10** [comment]
The attendence recipe was updated based on the template and issues. Those issues can be closed when we are happy.

I don't want to close this one as we are still waiting for student app data, so this is a 'bump' to remind us we are waiting for a template describing what student app data will look like
