### ISSUE TITLE
attendance - activity type clarification

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#151]
I think an edit might be helpful around activity type.

Firstly, it might be best to avoid using "ACTIVITY" because this is an xapi keyword. For the purpose of attendance, consider the object to be an event, with an EVENT_ID and an EVENT_TYPE.

Event type seems to work as part of the object. We have the object.definition.type for EVENT_TYPE
I don't see we need to have an extra EVENT_TYPE_ID.

This appears to be redundant: context.extensions.http://xapi.jisc.ac.uk/activity_type_id

Following on from avoidance of "activity", possibly change these to use "event"
context.extensions.http://xapi.jisc.ac.uk/activity_max_count
context.extensions.http://xapi.jisc.ac.uk/activity_mandatory

----
OK... now I'm going a step further, which actually contradicts some of the above.

Suggest we make the activity.definition.type indicate that these are "timetabled events" and use an exttension to indicate what kind of timetabled event (e.g. "lecture"). We could use the subType URI we already have to clarify the type of an application which is logged in to.

This will allow us to use the same statement template for "attended a meeting" while easily separating the those events from timetabled ones. Where we need the kind of timetabled event we use the subtype (this would be quite interesting from an analytical point of view)

**Comment by arc12** [comment]
I now see the example uses, although the text does now
"type": "http://activitystrea.ms/schema/1.0/event",

BTW - I was viewing the 1.0 branch

**Comment by ds10** [comment]
OK, I've commited some changes to the statement. We decided last week to include an example datastructure here which might help, I think @michaelwebbjisc was going to send it on to me.

Do you want a look at the statement? This is what I think you are saying?

- The properties with activity_xxx should be changed to event_xxx because activity is a loaded word
- object.definiton.type was lecture, which made the context extension activity_type_id redudent. I'm guessing activity_type_id is part of the data structure that we will be given? I too don't like event, I thought it was only for use when you didn't know the event type? I've gone with timetabled event like you have sugguested.
- Not sure I follow your final point. Your asking if the event is online or something then the subtype extension is used to find out the type of application that is logged in? Do you want to check the updated example? Do we get that kind of data from the tsv that is to be rolled out with 1.0?

**Comment by arc12** [comment]
David -

Yeah, thats about what I meant. (but a few ACTIVITY escaped the edit "ACTIVITY_LOGGED_START and ended at ACTIVITY_LOGGED_END")

re your last bullet. I was thinking something like
"extensions": {
            "http://xapi.jisc.ac.uk/subType": "http://xapi.jisc.ac.uk/lecture"
        }

Implication is that the documentation for "http://xapi.jisc.ac.uk/subType" should avoid talking about sub-genres of application, and instead talk about being a qualifier for the object.definition..type which it extends.
----
A few nits about the result, incl the documentation of "ResultC" on the common structures page; the URIs have got a bit out of sync and the table of properties needs to play catch-up. While changing, I'd be inclined to define extensions called:
"http://xapi.jisc.ac.uk/attendance_late" and "http://xapi.jisc.ac.uk/attendance_category"
rather than have "activity" or "event" in the names.
I know they are really only identifiers but these names feel more intuitive, as the result is that the student did or did-not _attend_.

---
I also wonder whether the attributes like max-count, mandatory, start/end are really context? would they not fit into object as extensions for the definition of the event which the student attended? That would bring context down to be just the module-context, which feels more obviously contextual ...
I think that would also allow for "http://xapi.jisc.ac.uk/event_type_description" extension to sit alongside the object.definition.type and http://xapi.jisc.ac.uk/subType extention. These all seem to be about the category of event, so putting them together on object would be neater.

**Comment by ds10** [comment]
I follow. I'll commit changes Monday morning. I would like to use the capital time at the call to go through this one of that's ok.

**Comment by michaelwebbjisc** [comment]
OK, might miss some of the follow.

Swapping activity for event is fine.

Agreed, need to capture that it's a timetabled event, and then what sort.

At the moment we're using object.definition.type to show it's timetabled:

eg
http://activitystrea.ms/schema/1.0/event  for a timetabled event

and then

"http://xapi.jisc.ac.uk/activity_type_id

to show its a lecture

not very elegant.

Agree that moving this to a single place from context to object is probably better.

so I think we are ending up with something more like:

  "object": {
	    "objectType": "Activity",
	    "id": xxxx",
	    "definition": {
	      "type": "http://xapi.jisc.ac.uk/event_timetabled",
	      "name": {
	        "en": "**ACTIVITY_NAME**"
	        },
	      "description": {
	        "en": "**ACTIVITY_DESCRIPTION**"
	        }
	      }

"extensions": {
	         "http://xapi.jisc.ac.uk/subType": "http://xapi.jisc.ac.uk/lecture"
	        "http://xapi.jisc.ac.uk/starttime": "**START_DATE_TIME**",
etc...
	        "http://xapi.jisc.ac.uk/recipeVersion": "attendanceV0.1"
	      }
	    },

is that right?

**Comment by ds10** [comment]
The commit looks like Micheals example, except I've left recipeVersion in context.extensions. Some other changes.

- Went with Adams "http://xapi.jisc.ac.uk/attendance_late" and "http://xapi.jisc.ac.uk/attendance_category" 
- I've left recipeVersion in context

**Comment by ds10** [comment]
From Monday: Jisc to check that recipe validates before closing recipe

**Comment by ds10** [comment]
I think @leebaylis was going to create some data against the attendence templates to check it is valid, then we were going to create some queries before signing this one off?

**Comment by ds10** [comment]
Notes from attendance review:

The datatype issues raised here are not quite right – I found the types on this page https://github.com/jiscdev/xapi/blob/1.0/vocabulary.md – but:
a)	Maybe other readers would miss these too, so better signposting or something
b)	Examples remain inconsistent with the vocab page
c)	I think event type id should be a string, rather than an integer

Also, I found an extension “event_timetabled” which is a boolean. I think something got messed up with the documentation of type/subType/event_timetabled. This definitely needs to be tidy, and clearly explained in the introductory paragraph to the template.

**Lateness flag is string**
The semantics are boolean. Example gives string. Documentation should be explicit about type (not just leave to example) and ideally be a JSON bool or integer 0/1 to match semantics

**Mandatory flags type not explicit**
Example gives an integer. Needs explicit type in documentation. Should be consistent with lateness.

**Event max count type not explicit**
Integer implied by semantics and by example. Should be explicit.

**Incorrect example for Object**
Object.definition.type is given as “"http://xapi.jisc.ac.uk/lecture", which is inconsistent with the documentation of ObjectD (and with conference call decision)

**Documentation on subType, event_type_id, and event_type_description needs review**
The permitted values for subType need some explanation. In particular whether a tutor-session is a subject-related tutorial or a pastoral event. If event_type_* relates to local institution event type coding, then that should be stated (both that these are meant to be from a list, and that the list is locally-defined).

**Check examples**
e.g. the context example contains a spurious “id” in the courseArea, with a Moodle URL
Object.definition.extensions in the full example contains data types which differ from earlier component examples (max count and mandatory)

**Comment by ds10** [comment]
I'm closing this because it has gone through the jisc xapi translater and issues are in seperate tickets now. I think one thing that the issues are showing is that the documentation is not clear. Data types/value spaces are in the vocab but not common statements so you have to go through 3 stages of documentation template->common_statements->vocab to check what the value should be. This also makes it hard to maintain because we can make a change somewhere, and forget somewhere else. Many off adams issues are 'which bit of the documentation is right?'

As part of the group of tickets that follow on from this I am going to tighten up the documentation so the 3 files link to each other better.
