### ISSUE TITLE
Statement template Versions

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#154]
Just to double check this as Alan and I both had a different understanding to the rest of the group.

All the statement templates in 1.0 are having their versions removed?
All recipes have a recipeVersion extension in the context. I take it this is to be removed since recipes no longer have a version. Should something similar take it's place (profileVersion)?

**Comment by MiroslavKratchounov** [comment]
My understanding is that we align all recipes to use the same recipeVersion in the context.
Eg. "http://xapi.jisc.ac.uk/recipeVersion": "1.0". This is how it is implemented from Blackboard.

**Comment by ds10** [comment]
Ok, my understanding was different:

- I thought that that recipeVersion held the statements own version number. We used to call statement templates recipes? So thinking about it, the URI doesn't make sense anymore if that is the case.
- So building on that, I thought recipeVersion was now going to be redudant. This was because 1. We don't have statement versions anymore and 2. We can't just stick the version of the spec in there because that doesn't match up with what it was used for

But you are saying that blackboard has always used the version number at the top of the README
(currently 0.5 in master, 1.0 development)? So there is no need to change (apart from make sure the examples reflect this, currently they follow my understanding that they match the statement version)

Is the the case for the attendance / student app recipes, have they also been using the version number on the README.md?

**Comment by arc12** [comment]
My recollection of the requirement(s) which led to the version numbers was that it would allow us to know the likely intention of the statement creator when looking at data. i.e. assuming that the likely intent arises primarily from an interpretation of the specification. There may, of course, be other identifiers for plugin (etc) release/revision.
The point of this is so that we can be selective in the case where data has been created to different statement specifications for what is ostensibly the same event. For example, suppose a documentation bug is fixed to change a URI for an activity type. For example, when  new extensions are defined. For example, when different permitted values change.

We did not originally have the idea of releases for the collection of recipes (e.g. 1.0). Arguably, that version fulfils a substantial part of the requirement. However, I think it may be incomplete, and that we maybe also should add an indication of the recipe and its version.
Rationale for recipe version = lets say *some* records had been invalidated and were to be replaced; would it be useful to know which should be deleted from the LRW prior to regeneration?

I am actually inclined to the inclusion of a recipe identifier separate from its version. This adopts the view that a "recipe" is a description of how a set of related statements hang together. e.g. VLE or Attendance (although that is only one statement template) or ... This might be helpful for querying or sub-setting.

**Comment by alanepaull** [comment]
Just checking about how to state recipeVersion. Like this?

 "http://xapi.jisc.ac.uk/recipeVersion": "1.0-2017-05-05",

 "http://xapi.jisc.ac.uk/recipeVersion": "1.0-ignore",

Alan

**Comment by ds10** [comment]
From Monday all: Mint http://xapi.jisc.ac.uk/version to recplace recipeVersion
