### ISSUE TITLE
Geolocation to attended

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#158]
From monday call: Geolocation to be added to attended recipe

**Comment by ds10** [comment]
I wasn't sure what was needed here, so I've gone with  http://id.tincanapi.com/extension/geojson which is a geojson object. If that does not cover what we want we can discuss this at the weekly call

**Comment by ds10** [comment]
I added the geojson to context.extensions because it seemed right. However, in ticket 151 michael sugguested we most the context.extensions to object.extensions in this statement template.

This has worried me a little bit:
- If all the extensions like starttime etc are in the object should the geolocation be in object
- Is the attendence then different than other recipes, extensions that are usually in context extensions in the object extensions, and if so then the inconsistancy will make life hard?

**Comment by arc12** [comment]
I can see three arguments (David's worries +):
1. put the geojson where the other informative extensions are for a given statement template
2. put it where a semantic argument tells you
3. always put the geojson in the same place

Maybe we get different answers, maybe not :-)

for attendance:
A1 = where start time is
A2 = in object.extensions if we see the location as being about the event, in context if it is more incidental. I think here, probably it is not incidental (but e.g. the location from which I accessed a VLE obn my phone would be contextual as the location is incidental)
A3 = I guess we can choose. in context probably because that seems less odd for the mobile device location use case.

I think object.extensions has it by a nose... but others might weight #3 more highly.

Adam

**Comment by alanepaull** [comment]
I've been trying to check out this difficulty, because it may cut across much of our recipe design. In this post, I'm talking about stuff in relation to an assignment as an Activity object, but the general concepts should apply across the piece. From https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#miscext:

"**4.1 Extensions
[snip]
Extensions are defined by a map and logically relate to the part of the Statement where they are present. The values of an extension can be any JSON value or data structure. Extensions in the "context" property provide context to the core experience, while those in the "result" property provide elements related to some outcome. Within Activities, extensions provide additional information that helps define an Activity within some custom application or Community of Practice.**"

This seems at least partly helpful, though I would find it more helpful if folks didn't persist in defining "context" by using the word "context" as a central part of the definition :(.

So, extensions should relate to the part of the Statement where they are present. This should mean that an extension related to an Activity object goes into the Activity object. Of course, that begs the question of how we interpret 'related to' versus 'in the context of'. However, I would argue from a plain English interpretation of 'related to' that the geolocation of an Activity relates directly to the Activity; it's not merely context, it's where it actually takes place. Therefore, I would put it as an extension into the Activity object, not the context.

In contrast the Umbrella Course Area is part of the wider context of, not directly related to, the Activity object - I'm talking about an assignment here - so it (correctly) goes into the context, along with its identifier vle_mod_id. I think we should consider more explicitly the xAPI description from the spec as we make these decisions, or we may get tied in knots.

I think I would like us (me?) to look more closely at where extensions are placed, so that we can correct ones that may be a bit questionable for v1.0; or at least raise them as issues.  For example, in v1.0 attendance, we have http://xapi.jisc.ac.uk/uddModInstanceID in an extension to the Activity object for a timetabled event. This should more properly be in context - it's conceptually equivalent to vle_mod_id, which *is* in the context.

**Comment by ds10** [comment]
Looking the my notes from the week I couldn't make it and there is some discussion about 'context is about devices'.  I wasn't sure there to be sure what to make of this, but is this guidance to where extensions should be placed? So in this case geo information is about the event and not which platform is used to attent the event, so it would be object.extensions in this case?

I could have taken the wrong idea from the notes..

**Comment by ds10** [comment]
from monday call, because this is looking for where the student is (device location , and not event is) it is context.

**Comment by ds10** [comment]
from monday: mint jisc extenstion, devicelocation
