### ISSUE TITLE
http://xapi.jisc.ac.uk/externalURL rather than http://xapi.jisc.ac.uk/vle/externalURL

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi#162]
I'm pretty sure this is a documentation error:

In the vocab, externalURL doesn't follow the pattern of the rest and is 

http://xapi.jisc.ac.uk/externalURL

rather than 

http://xapi.jisc.ac.uk/vle/externalURL

**Comment by ds10** [comment]
Could it be because externalURL isn't a VLE 'thing' and could be an external URL in any platform?
Happy to change this, but I'll leave it for discussion on Monday, as I think its a quick check and fix.

**Comment by michaelwebbjisc** [comment]
yes, i did wonder if it was because it wasn't a vle thing, but then the same applies to other elements.

**Comment by arc12** [comment]
As a general principle, I favour semantics and names which are general rather than application-specific.
an external URL feels "not a VLE thing" but a VLE course area "is a VLE thing". Arguably, a quiz in a VLE is no different to that in a simple e-assessment tool, but not all e-assessment tools are just vle-like.

I note that Bb have used the documented URI, without "vle" in the name.

I conclude: the current doc URIs represent a judgement call which is not wrong and should be left as it stands.

**Comment by michaelwebbjisc** [comment]
I think it was done by mistake, rather than judgement, as we've not been consistent. I don't feel strongly either way though.
