### ISSUE TITLE
subType

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/xapi#166]
I've been looking at generic statement templates, and I don't quite yet understand subType.

There are various indications that subType is used as given in the Vocabulary document. However, that simply defines it as "Identifies the sub genre of any application" with only 1 example (and that example is defined in tincan as a platform). Do we have a list of subTypes somewhere?

Alan

**Comment by alanepaull** [comment]
Some of my confusion may be caused by Moodle and Blackboard variously described as "platform" and / or "application".

Example
```
"object": {
  "objectType": "Activity",
  "id": "https://courses.alpha.jisc.ac.uk/moodle",
  "definition": {
    "type": "http://activitystrea.ms/schema/1.0/application",
    "name": {
      "en": "University of Jisc VLE"
    },
    "extensions": {
      "http://xapi.jisc.ac.uk/subType": "http://id.tincanapi.com/activitytype/lms"
    }
  }
}
```
This object is used in login. I'm not sure why we need the subType extension here. Wouldn't it be simpler to put "http://id.tincanapi.com/activitytype/lms" into definition.type? That would mean 'Student logs in to LMS'; and the Context can carry context.platform = Moodle, for human readability, while machines can read id="https://courses.alpha.jisc.ac.uk/moodle".

I guess there is a reason for this structure. I would be grateful if someone could enlighten me!

**Comment by arc12** [comment]
I suspect the origin of this is an activitystreams pattern but I think the rationale is OK.

People may log into PCs and into software. object.definition.type will discriminate between these two while the verb logged-in remains the same. Having "application" as the type rather than VLE means we can easily query over several applications as aggregate activity. e.g. a portal, separate forum, vle. The subType gives us the ability to drill down should we need to.

The application type is a VLE. We hava generic subType extension which can be used to communicate the more refined type of application, or whatever other object.definition.type may be in the statement (i.e. we only ever need to look in subType, no matter what the parent type)

We might have two Moodles. Each would be subType = vle and both would be platform=Moodle. But their object ids woud differ.

We might have Moodle and Blackboard.... platforms differ.

We would assume that the Moodles at different sites are generally fairly similar but also expect that Bb would differ from Moodle in the usage patterns. Hence platform is useful not just for people.

**Comment by alanepaull** [comment]
Ah, so it's primarily differentiating between logging into PCs (or other hardware) and into software? And then for easy parsing of all the 'application' ones.  That makes sense.

**Comment by ds10** [comment]
From Mondays Call:
- Clarify subtype in documentation. (These will be advised by domain specific experts. These might be generated on the fly.)
- Group vocab,  Group what we already have, produce an hirarchy of type and then subytpes. We need input from domain experts here!
- Subtype is wrong in the vle resource viewed statement. Update this when the documentation is updated.
- mint a new activity type 'Other'

Related to #163 #144

**Comment by ds10** [comment]
Quite a few tickets, #166, #163, #144 and the development of the repo need the vocab hiraichary we discussed on May 22nd. If I remember correctly, this requires some domain experts to go and have a look at the vocab page and split the activity types into core and subtypes. I've updated the vocab page so that we have headings for activity types and subtypes. I think it needs a bit more documentation too - but the activity types need sorting.

I'll add this to todays call to check, we are on the same page.

**Comment by ds10** [comment]
Just bumping this issue: I think domain experts were going to have a look at the vocab page in v1.0 and start to group activity types into core and subType? This is a bottleneck for quite a few issues I think. This week we only discussed UDD so didn't get to bring this up. I seem to remember the discussion was @alanepaull @arc12 @michaelwebbjisc . I've created a subType section on the vocab page, but I think we need some domain expert input here.
