### ISSUE TITLE
Statement template tables

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/xapi#187]
We're not consistent (yet) about whether we put the details of the properties in the entity section or not. Sometimes we do, but we commonly refer out to the common structures document, and commonly we rely on an example. However, frequently the common structures document doesn't match with the statement template, and the examples are often not comprehensive.

I suggest the following rules:

1. We *always* put the table of properties in the template, for the avoidance of doubt.
2. Any example *should* be maximal, so that folks going from the example include everything they might be able to include.
3. Where an example is only 1 of many possibilities, we say this appropriately with the example.
4. We *can* reference out to the common structures document, if we're indicating that the table of properties is based on one in the common structures document, but it's not essential.
5. We *should* refer to the vocabulary document where there is more information there (as I think we already do).

Views?

**Comment by arc12** [comment]
The common structures document serves 2 purposes:
1. single point of documentation (for document internal consistency)
2. avoidance of arbitrary differences with no functional benefit (a consistent approach for devs and data users)

The issue here is that we're not really using the correct tool for the job. REALLY, these bits of specification should me maintained in one place only, and included by reference. Copying into each template may be helpful for readers but it increases the chance of there being multiple inconsistent bits of text. Furthermore, the examples should really be unit-tested against the specification.

So... if we go the way of #1, I think the common structures document should remain, and be the NORMATIVE structure. Anywhere where the structure is used SHOULD refer to the structure by its identifier, and if the information is repeated in the template, a note made that this is INFORMATIVE. There is then an onus on whoever maintains the spec to ensure that any change to the normative text is cross-checked against all identified uses.

I'm sceptical about that being viable. I think we should look at alternatives which use the idea of the common structures but which handle it differently in the documentation. For example, we could break up the document to make it more usable. We could replace the table of attributes with something easier to read. We could invert some of the organisational logic and put template-specific info/examples in the same file as the normative structure, rather than in the template markdown (which then becomes more of a description of how parts fit together + full minimal/maximal examples). Just thoughts...

As to examples: maybe a minimal and maximal example? Also, both example fragments + an example whole statement? The former helps to explain what is specified, but the latter is likely to be taken as The Template in some dev situations.

Overall: I agree we don;t have an optimal approach yet. (and I acknowledge that aspects of the inadequate way we do it now are based on my earlier contributions)

**Comment by arc12** [comment]
OK... re "We could replace the table of attributes with something easier to read" I see that the attribute tables now have nice rows! much less taxing on the grey matter ;-)

**Comment by arc12** [comment]
Following on the thoughts about refactoring around the common structures.

by "break up" I was thinking into separate md files for the principle xAPI secton e.g. verb, context, object

I think we could also rationalise the common structures doc a little.
Idea: e.g. contextA is the basic structure, then describe context C as being contextA + additional information. That makes it more clear what is REALLY common.
Following that through, objectA could have the subtype removed from its definition, to keep objectA as being the common core (as it originally was).

Maybe we have over-cooked the idea of common structures too. For example, if objectN is only used in template T then why document it as a common structure? We could just refer to objectA and say, in template T documentation, "object for T extends objectA with ..." IF at some point we have another template U wanting the same structure, we refactor "object for T" to be common objectN and refer to it from T and U.

**Comment by alanepaull** [comment]
I think that my underlying point was @arc12's last paragraph. Where a structure is commonly used across templates, then it's a common structure. If it's only used once, it's pretty much not common by definition. So, I agree with the approach in @arc12's last sentence.

If that's OK with others?!

**Comment by ds10** [comment]
I think a problem with common structures is that currently it is making documentation harder rather than easier to maintain – perhaps because it has an unclear purpose. During development an entity in a statement template changes quite a bit, and sometimes what was a very different looking entity suddenly looks very much like a previous common entity with perhaps just a little tweak. So, during development you have to either keep evaluating where you are with the entity or not fill in the common_structures document until you are close to finalising the statement, this leads to inconsistencies in the documentation, including common entities in the documentation that are currently not even being used. I think this has been harder in 1.0 because this is a development branch - but statements are still being used to feed the LRW.

**Comment by ds10** [comment]
Tables are now in statement templates, unless they are actually common - verb, actor etc
