### ISSUE TITLE
extend CourseArea

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#199]
This is motivated by the availability of course instance information in attendance data for D&G where as module instance data is not easily obtained with complete coverage. 

Propose:
A. https://github.com/jiscdev/xapi/blob/1.0/vocabulary.md#coursearea be extended to include the UDD COURSE_INSTANCE_ID (will also need to amend "properties in courseArea must be a UDD Module Instance ID or a VLE Module ID or both")

B. The documentation for VLE indicates one or both module instance id must be provided

C, The documentation for attendance indicates course instance id must be provided and the module instance id provided if it is available.

This should make for more robust computation of course level attendance when more than one course is in progress (more an FE than HE situation).

**Comment by ds10** [comment]
This has been commited to [1.0.1](https://github.com/jiscdev/xapi/commit/120f1f1f0a3108a4622b79baa296820d8434fa38)  because it requires no changes to the plugins:

- Vocab has extended coursearea to include a uddCourseInstanceID
- VLE statements and VLE statements in common_structures have stayed the same (perties in courseArea must be a UDD Module Instance ID or a VLE Module ID or both)
- Attendance statement now asks for uddCourseInstanceID and uddModInstanceID
