### ISSUE TITLE
Timestamp property and vle resource viewed

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/xapi#214]
We have a somewhat mixed situation at present, I suspect because documentation is slightly out of kilter with practice.

The statement template (https://github.com/jiscdev/xapi/blob/1.0.1/recipes/vle/Module-View.md) doesn't have the timestamp property. Both Moodle and Blackboard examples have it. Moodle also has "stored", Blackboard doesn't.

Proposal:

(i) update the statement template to include the timestamp property, defined as "The time at which the user viewed the resource." Update UxAPI files accordingly.

(ii)Leave "stored" as a purely implementation issue, as this is to do with the time at which the data was put in the Learning Data Hub.

**Comment by ds10** [comment]
To discuss at weekly call.  Alan has added timestamp to UxAPI, but Timestamp has never been in the statement template. Not sure why this is the case.. add it and close?

**Comment by arc12** [comment]
I suspect that timestamp was obvious when we started, part of the core xAPI spec and trivially identified with the time an action was recorded.
As we've gone on - e.g. attendance - it isnt so obvious when the timestamp should be. xAPI spec notes that it depends on the activity.

My conclusion - its not always obvious so we should be explicit in all statement templates.

Additionally, when I was editing the attendance TSV binding, I actually *removed* timestamp since the statement template documentation said it was identical to the event start time. The expander templat then just uses the start time from the TSV. That should, I hope, enforce the semantics of timestamp for that kind of activity.
