### ISSUE TITLE
Convention for TSV fields leading to URIs in statement template

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#215]
These comments are based on those originally added to issue 21 in the universal-xapi-expander repo but are now repeated here because the TSV documentation is part of this repo. "Based on" means not the same; include some thoughts from a skype call with Michael Webb 2018-01-04

We have 2 uses of URIs in statement templates which are relvant to this issue:
A. use for controlled categorical lists
B. use as identifiers

Note that sometimes we might have de-facto categorical values which are not defined in the statement templates and where simple strings may be used. For example the attendance code. While this could have been defined as a URI, there is no benefit because the codes have a "local-only" de-facto namespace.

Proposed approach (some form of this for the documentation)...

Concerning A:
The preferred option is for the TSV to contain only the last part of the URI, for example a URI for an event type may be "http://jisc.ac.uk/events/lecture" and the TSV would contain "lecture". This will work where there is a common or default stem for the categories which may be usd for a given attribute. This should be documented in the TSV binding (and would be hard-coded into the universal xapi expander)

Where this is not feasible for all URIs for a given attribute, the TSV may contain a full URI only for those cases where it is not feasible to use the preferred option (only the last part supplied).

The TSV binding documentation will indicate when the non-preferred approach may be used.

Concerning B:
The TSV should contain the simplest source system primary key. When the TSV is used by e.g. the xapi-expander, it will be down to behaviour of that system to compose the URI from institution domain and source system identify metadata (which is not in scope for definition here)

My motivation is primarily that I feel that the best option for getting usable data is to avoid a requirement on the people doing the ETL to get to grips with this aspect of the recipes. i.e. I feel we should be as close as possible to the databases and to simple lists of permitted codes.

**Comment by ds10** [comment]
To discuss at weekly call (related to ticket #211):

- Alan and I have added templates and TSV inputs for each statement template. I want to nail down the conventions of this approach and see how it works in practice asap, especally since we want to be reviewing/finishing the new 1.0.1 statements soonish.

- Adam has made changes to the attendence inputs and templates. Some of these changes are attendence specific and some more general as discussed above.

- Since we have data ready to go and Adam has made his sugguested changes -can we use attendance to test the process/procedure etc before 

- Any other discussion about the TSV and templates. Do we need all the information in the tsv definitions? I'm thinking purpose and derivation might leave scope for things going out of sync?

**Comment by ds10** [comment]
Weekly: decided to go with these conventions for each each statement template in 1.0.1

See tickets #219 #220 #215
