### ISSUE TITLE
Add intervention to 1.0.1

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#230]
Intervention to be added to 1.0.1 see intervention feature branch and start with TSVs.
Three statement templates - start with TSV definitions

What we want to record:

1. Create activity (verbcreate)

Mode (email/text/telephone intenal list and institution cnan have their own)
Reason (match traffic-light list?) Subtypes if insitituion has their own etc
Timestamp
Weighting (1-5 severity)
Tutor (tutor id)
Start dates, end dates (leave these to 1.0.2)

2 Closed activity (verb close)
Item id
Tutor id
Verb that they closed it

3. Updated activity (verb updated)
Item id
Tutor id
Add Note
Change sevitory
Type (note or sevitory)
Verb updated

**Comment by ds10** [comment]
- Double check. whay these categories, how do they fit in to what adam/tribal already have
- hold off on json templates etc until confirmation

**Comment by ds10** [comment]
I'm just about to commit a first stab at  'notes'. There are a few ways this could work, but I think working out which is the most practicle depends what exactly notes are (are they a jisc thing or more general?) and how they will be analysed. This is what I've commited so far:

- Create: A note (http://xapi.jisc.ac.uk/intervention/note) is created (Verb: http://activitystrea.ms/schema/1.0/create)
- Update: A note with the same object.id to the inital note is updated (Verb: http://xapi.jisc.ac.uk/update)
-Close:  The note is closed (http://xapi.jisc.ac.uk/close).

Other ways:

- Create: A note ("http://xapi.jisc.ac.uk/intervention/note") is created (Verb: http://activitystrea.ms/schema/1.0/create)
- Update: A note with a different ID to the inital note  is created ( and the parentnote is uses context.contextactivities.parent to show which note is updated.
-Close:  The parent note is closed .

In each of these I've put the student that the note is about as the actor and included the instructor in  context.constructor. I think we've had conversations about this before with marking and the such?

**Comment by arc12** [comment]
Re the actor:
I do like the idea of having the student as the actor, from the POV of LA, because it always puts the student in the same place, making for consistent query formation and data processing. For assessments this was OK because we could use verbs like submitted and scored. In the current case, I fear we'd end up with either:
a) broken subject-verb-object semantics if subject = student and verb=create
b) a convoluted pseudo-verb for "had something created about"
So... it might be the lesser of two carbuncles to make the staff member be the agent.

Re object id continuity vs parent id:
I see 2 things to identify, the "case" and individual "notes". The case is opened and closed, and maybe updated (e.g. change category). The notes capture comment and interaction modality. I think the continuity here is in the case id, i.e. == the object.id. xAPI statement ids OK for individual notes.
Avoidance of context parent makes for easier data handling.
So... the way I'm now seeing this is to model the process as create/update/close a case and add a note to a case. Update is exactly the same template as create (except different verb) but adding a note is just a comment. This would leave the data processor to figure out what changed in an update and whether that is important (e.g. change in severity). An alternative would be to mint verbs for things like change of severity, which seems OTT at present.

**Comment by ds10** [comment]
Weekly call:
Follow adams ideas
- Person creating note should be actor.
- Open case - add comments - close case. Case is parent, notes belong to case
