### ISSUE TITLE
quiz_completed: result.duration undefined in jisc profile

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/xapi#254]
To be added to quiz_completed.md#result

Also, not present in TSV. This may be correct, as duration may be a derived property. To be confirmed.

**Comment by arc12** [comment]
isnt this optional, ergo not a "bug"?

was the requirement for duration on quiz something which came up on a call? Durations are rather slippery concepts...

**Comment by alanepaull** [comment]
I put it as a bug, as the only mention of it was in an example - not actually in the spec; including not as optional/mandatory, and so on.

**Comment by arc12** [comment]
suggests to me the example is wrong, probably generated by code.
I content that examples are non-normative, illustrating the spec rather than defining it. We have previously got into trouble by allowing the spec to be defined by examples coming out of plugin/vle X.

In this case we could, I suppose, leave duration in there and note that it is emitted by some system or other, even tho not in jisc recipe, but this is OK as the principle of xAPI is to allow extra content.

**Comment by alanepaull** [comment]
I was insufficiently clear. It's in the TSV and JSON specs, but not in the quiz_completed.md (the main statement template specification).

I think we need to decide whether or not to put it as optional in the main spec, because inclusion in the translator suggests that it's either in use or expected to be in use.

**Comment by arc12** [comment]
A test for inclusion:
1. the data is available and useful in at least one major source system
2. we want people to spend the time and effort to a) extract/create the fact in source data and b) to write code to support the fact in downstream analytics/visualisation software

if (1) and (2):
  include in main spec
else:
  remove from example/tsv/json

**Comment by ds10** [comment]
From call: remove from all
