### ISSUE TITLE
Monitoring attendance over multiple, split events

### ISSUE THREAD

**Issue by alleycat58uk** [jiscdev/xapi#262]
The attendance monitoring appears to use event or timetabled event as a single instance whereas, in reality, they may consist of multiple instances.

**Scenario**
Lecturers arrange a timetabled event with Librarians to cover the required information literacy skills prior to researching material for a dissertation.  To make the session available to as many students as possible, the event may be offered once as a morning session, once as an afternoon session and once in the evening.  Students would only be required to attend one of the three sessions and the choice of session would be theirs.

Could the multiple 'instances' be recorded so that _overall attendance_ at the event could be measured?  For example, in the above example, could the first instance be noted as "1 of 3" with links to the other 2 instances?

**Comment by arc12** [comment]
There are several ways to model this kind of thing. the one adopted is that the entity being described is something with location and time. It is a slot in a calendar/diary. this makes it quite a general thing without the specification needing to entertain business rules like in the scenario you give, and not being specific to timetabled events (e.g. it could apply to an ad hoc arranged meeting).

From a data-processing point of view, I like this simplicity, and from many years trying to write specs which model the non-simple, I know it can be hard to accommodate all the use cases in concrete terms in the core model. I think it is often better to decorate a simple statement with extensions.

For example, in the above scenario, I argue that these are legitimately three instances which students are expected to attend only one of. I can immediately see two additional pieces of information which you might wish to include:
a) an identifier for the abstract event, the thing designed (equiv to an OO class), which could be applied to all event instances
b) a business rule which is "should attend one of", which maybe outside the scope of an xAPI activity statement

Depending on the way this is delivered, it might be that students sign up. In which case we could indicate non-attendance at a mandatory=0 event. But what happens if they attended a different event to the one they signed up to. If it is purely drop-in with recording of who turns up, we'd only see records with attendance=True. Or maybe there would be a trigger in the attendance/timetabling integration which records attendance=False for the last event if none were attended. Already we are starting to get into a bit of a mess with extra detail: is there sign-up, how is recording being managed.

in the face of this, it is probably best to stick to the lowest common deonomiator:
record all three events as xAPI statements with mandatory=False
record attended as True/False for each

and to include a "class type" identifier as an extension so anyone who knows the inner details of how things were done could work out the stats

**Comment by alleycat58uk** [comment]
Thanks @arc12, and yes, I agree this is a complex case that could be modelled in several different ways. And I like simplicity too!

I do have a couple of questions which probably arise from gaps in my knowledge.  Would it be possible to schedule a call to bring me up to speed? To give this some context, I have been brought in to look at the application level use of this data in UoG.

**Comment by arc12** [comment]
In the interest of transparency, I may not be the best person, as I'm not representing Jisc; I work for Tribal, involved with transforming the data for use in our predictive analytics system. This gives me a particular perspective: writing clean, reliable, and maintainable code which works across multiple institutional contexts.

Happy to talk, but it might be better to do so with someone from Jisc or David Sherlock from Cetis.

**Comment by ds10** [comment]
Hi @alleycat58uk, sorry I was on leave the week you left this comment. Do you still want a chat? I maintain the Github and meet with Jisc reguarly for decision making and review. I could try and answer your questions at a first, and then if still you want jisc input we could try getting @leebaylis or @gmoger-jisc involved?

**Comment by alleycat58uk** [comment]
Hi both and thanks for the response.

The main reason for raising this here is because I need to better understand the data structure as defined by the attendance recipe.  This will necessarily raise application level (and cross institutional level) discussions but I need to start at the data structure and work up as this constraint has already been set.

Can I suggest a call with David, Gareth and myself?  I can be available Friday or Monday.

**Comment by gmoger-jisc** [comment]
That's fine - let's move this to email to arrange times.
