### ISSUE TITLE
Review e-Content recipe

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/xapi#271]
I think the e-Content recipe needs to be reviewed as we are not able to capture the required data from any data sources such as exproxy.

From ezProxy what we can capture is:

- Student

- Time

- ULR

- Host name

Trying to capture more details such as journal title/type is too inconsistent using the current tools available (such as ezpaarse) e.g. not all all log items will be direct links to content and could just be urls to a provider like ProQuest.  Even where they are direct links, parsing additional contextual information only possible on a small percentage of records (in my testing with Gloucestershire data).

Can we discuss this on our next call?

**Comment by ds10** [comment]
I think Lee wrote out the original requirements for this, but he was very much in a discussion and testing phase.

Happy to discuss this at the next call

**Comment by gmoger-jisc** [comment]
Yes he did but I have now taken it over.  From my testing it is not going to be possible to obtain most of this data.

**Comment by ds10** [comment]
Yes, I understood that it was explority and hadn't been tested in the field yet. Do we have feedback for the other library recipe. borrowed item yet? Does that need looking at also?

**Comment by gmoger-jisc** [comment]
That one is fine and has been used for 1 of our institutions.  The OCLC number still raises some questions in my mind however but is not a concern right now.

**Comment by ds10** [comment]
Going to have a stab at this in 1.1 branch

**Comment by ds10** [comment]
I'm having a stab at this in 1.1

Can I double check about the things you can capture, is ULR just a typo of URL?

**Comment by gmoger-jisc** [comment]
Yes, it should be URL :)

**Comment by gmoger-jisc** [comment]
Do you have a provisional recipe I can use for this?  I want to test translating the data from the ezproxy logs into the potential format.  I can put something together but don't want to duplicate work if you already have something.

**Comment by ds10** [comment]
sorry, I haven't tagged the commits with this isue number, 1.1 branch has a new econtent recipe. It is basically cut back to 4 items you highlight.

**Comment by gmoger-jisc** [comment]
Can I just confirm the thinking here:
ITEM_ID = URL
PLATFORM = Host name

As an example this is the data we have from the logs:
Time = 2018/09/30:01:30:07
IP = 12.34.56.78
Student = 12345678	
Route = proxy
Hostname = www.dawsonera.com
URL = https://www.dawsonera.com/abstract/9781137029317

**Comment by arc12** [comment]
I think (and confess to not having studied the econtent realm) that the platform would more usefully be the  econtent proxy. This gives us the potential to  bundle records up with knowledge of only a fairly small (and stable) list of platforms. For example, if there is only one econtent proxy i use, but potentially many and changing providers of content then I would like to query by the platform "ezproxy". The content provider would, in this case, go somewhere else in the statement

**Comment by ds10** [comment]
context.platform is described by the spec as: _Platform used in the experience of this learning activity_, so for the VLE statements it is Moodle or Blackboard.

I'm not sure how students access econtent, but it looks from your log like the we don't have that information, unless it is 'proxy', but I expected a specific platform.  I guess the hostname may not be the platform delivering the econtent? It is optional in the xapi spec.

ITEM_ID, is an iri for the object. I think Lee contributed to the way the iri as it is constructed in the 1.1 branch. I think it is constructed by parsing data he had in the logs (**HOMEPAGE**/library/**ITEM_ID**").

In your logs ITEM ID may have been 9781137029317. But I'm not sure that this way of doing it is correct, because the iri would then be the same for students from the same institution, but not for students from different institutions (because they would have different homepages)?

**Comment by gmoger-jisc** [comment]
I will need to think about how to generate the ITEM_ID then as there are no unique identifiers we can use.  It will perhaps be a concatenation.  The example I gave above is more simple and you could extract an ID but this will not be the case with all URLs which might be searches such as:
https://www.ncbi.nlm.nih.gov/entrez/query.fcgi?db=PMC&cmd=Search&term=0007-1447[jour]+AND+2[volume]+AND+1170[page]+AND+1950[pdat]

Or routing to their account:
https://uni.on.worldcat.org/myaccount

I think then we are missing somewhere to store the hostname which I think is the most useful point for analysis.  This should come in the object section.

Whether or not we need the full URL is another question.

Agreed with Adam that platform should be the proxy system or wherever we are generated the content from.  This might be ezproxy, other proxy systems or library systems.

**Comment by ds10** [comment]
Also agreed on context.platform being proxy system and not hostname. Extensions are allowed in activity.definition . Are their any opinions on how this should look in there? It feels like there should be a sensible way to do 'host of activity', but this in the [registry](https://registry.tincanapi.com/#uri/extension/505)seems overkill..

**Comment by gmoger-jisc** [comment]
I don't think the 'host of activity' is the right fit here.  Looking through the registry I cannot see anything that meets our needs.  Can we add something?

**Comment by ds10** [comment]
I'll mint something with xapi.jisc.ac.uk in the dev branch (1.1) for now, to review at next call?

Things to review at next call :

- new template in 1.1 for econtent viewing, in particular:
- 1. the hostname property in object.definition.extensions
- 2. usage of context.platform
- 3. structure of object.definition.id

**Comment by gmoger-jisc** [comment]
Yep sounds good.

**Comment by ds10** [comment]
As with the other tickets, I've updated the json template, but not the .md description until we've ironed it out at the call

**Comment by gmoger-jisc** [comment]
I want to review where we are with this recipe generally as I think it has evolved quite a lot since looking at more data and understanding e-resources.

Libraries refer to e-resources as meaning journal and other publishing content providers.  There are 2 routes for tracking access to this content:

1. institution authentication logs (much like RAPTOP https://iam.cf.ac.uk/trac/RAPTOR/wiki)
2. content provider usage statistics (submitted to JUSP https://jusp.jisc.ac.uk/)

The JUSP data is no good here as it is anonymised and aggregated at the point of submission so we cannot capture an individual students engagement.

Institutional logs such as those from ezproxy, shibboleth, open athens etc are what we have to work with.  

The scope of this recipe then is to capture student engagement with with e-resource providers, where engagement is determined by authentication to the resource.

Can we agree on an appropriate name for this as I don't think e-content is sufficient.  Maybe "e-resource authentications"

We may also need to review the verb as we cannot say that a student has viewed a particular piece of content.  Instead we can say they have "accessed" a provider (or host as described in the data).  There is a verb for accessed but maybe you can advise if there is anything more fitting.

The structural questions can also be discussed on the next call as outline by David.

**Comment by ds10** [comment]
ok, as far as I understand it, micheal pushed for this in 1.0.1, but it isn't being used and now we have had more data over the past month or so it has got a little confusing, so I am going to sum up the situation for the call to make sure I am on the same page.

- The master branch (1.0.1), holds the 'viewed econtent' statements, this ticket was opened originally because Jisc don't have the required data for this. When we put it into the master branch, we were aware this might happen
- A new attempt at was  mocked up in (1.1 because it is not backwards compatable, although we aren't actually collecting this yet), using the items described in the original post of this ticket
- Since Gareth has access to more data now it needs a review. Here are the issues as I understand it
- This may be more than a viewed statement since it may capture different interactions with e-resources

So, I'll review the raptor documentation before our next call and it would be good if we could talk about what the statement is. But, it sounds like it could be a e-content recipe with viewed being one statement of many?

**Comment by gmoger-jisc** [comment]
Not sure I understand the last paragraph but I am thinking that this will actually be 2 recipes. Right now we only have details on 1 as outlined in this ticket (e-resource authentication).

The second might capture 'viewed digital resource', where it is something tracked by the library management system such as items in a special collection or media.  In this we would be able to capture more detail as outlined in the original recipe.

**Comment by ds10** [comment]
yes, the repo has recipes that are a collection of statements, e.g the VLE recipe has a bunch of statements related to VLE activity. So I am sugguesting that 'ezproxy, shibboleth, open athens etc' might be a eresources recipe that has a bunch of statements. We haven't looked in to it yet, but I am guessing that perhaps the viewed statement is still useful, but we also need other ones as part of a larger recipe for dealing with eresources, such as an authenticated statement.

**Comment by gmoger-jisc** [comment]
Yes that makes sense.

**Comment by ds10** [comment]
For November 5th call:

1. Do we need a recipe that is for econtent (or is it library econtent) and are the library statements around physical library? Are the reusable templates useful. How is econtent seperate from VLE?

2. We are all agreed context.platform the proxy?

3. What does the object.id look like? I think Lee stabs is wrong, he is doing a bit of regex, homepage + "/library/" + item_id , I think this is incorrect...

4. Where is hostname stored, currently stored object.definition.extensions.http://xapi.jisc.ac.uk/hostname in the JSON template

**Comment by ds10** [comment]
From call:

- We might two statements viewed and some kind of authenticated/statement/provider (access) statement:
- Viewed statement is ok, but has limitations, this needs hostname
- The 1.1 viewed statement is actually the base of a 1.0.2 access content, and viewed from 1.0.2 might be ok. 

- we agree that context.platform is not the hostname

- some form of regex from url for object.id ? hostname + something? 

- hostname is fine

**Comment by ds10** [comment]
changing this from 1.1 to 1.0.2 because this is now a new statement and  viewed is not changing

**Comment by ds10** [comment]
The 1.0.2 branch has now split econtent in to viewing and access statements. The viewed statement is the original viewed statement and accessed has a new verb (http://activitystrea.ms/schema/1.0/access) and is the 'new viewed' statement that we had been working on.

I think the work to do is to check what data Jisc have and if this approach is going to work.

Slightly confusing that in the 1.1 branch viewed was going to be a different statement with the same verb, I'll update 1.1 with the 1.0.2 changes early next week if nobody shouts.

**Comment by gmoger-jisc** [comment]
Confusing but I think I understand and will see how it all looks next week.

**Comment by gmoger-jisc** [comment]
Can you give me a direct link to the provision 'accessing e-content' recipe?  I'm probably just looking at the wrong branch but struggling to find it.

**Comment by ds10** [comment]
You can find both the older viewed and the new accessed in 1.0.2 onwards, perhaps we should talk about the structure of the repo and releases at an upcoming call...

direct link to JSON template: https://github.com/jiscdev/xapi/blob/1.0.2/recipes/library/uxapi/library-accessed-econtent-template.json

**Comment by gmoger-jisc** [comment]
Thanks David.  This looks fine to me.  Is there anything on your side preventing it from being finalised?

The only issue I have is on how I am going to form ID but I will figure something out with it.

**Comment by ds10** [comment]
By finalised do you mean releasing it as part of 1.0.2? If everyone is happy with the statement(we haven't ran the verb past the monthly group yet etc) I am happy to push it out as part of 1.0.2.

Most of 1.0.2 is ok I think, the exception being the Setting and Reaching Targets recipe which was on hold. I think they were going to be worked on at the same time as a Jisc targetting setting application? They would need pushing back to 1.0.3 or a feature branch?

**Comment by gmoger-jisc** [comment]
Yes, releasing.  Were there any other options for the verb that you found?  I would still prefer to have something like 'authenticated' as opposed to 'accessed' but it's a subtle distinction that may not matter too much ultimately.

Authentication - the process by which you verify that someone is who they claim they are.
Access - the process of enforcing the required security for a particular resource.

Let's just make sure to capture what we mean with this recipe and that 'accessing' is a user authenticating for resource.

Setting and Reaching Targets recipe can be pushed to a separate feature branch as it is not being worked on by anyone right now and I don't want that to hold us up with this.

**Comment by ds10** [comment]
Just thinking as I type a bit here:

We may need to think about this, the verb will depend on the actor and the object, at the moment the student is the actor, the object is resource and the description of the verb is:

'Indicates that the actor has accessed the object. For instance, a person accessing a room, or accessing a file.'

The actor here doesn't authenticate or enforce security? As far as I understand, in the current statement template that is done by the proxy in the platform?

So, I think we should be really careful about what is authorising what, if the actor was authorised by the object, then that mean that the object would be the proxy (instead of the resource being accessed) and we would have to be really careful with the verb. Then again, that approach feels backwards to the xAPI spec because the actor preforms the action, so following the spec, should the proxy be the actor? Tgat approach feels backwards to the Jisc spec..

Would appreciate the groups thoughts on this one

**Comment by ds10** [comment]
just reviewing other statements and thinking about this. Is this more like

"actor logged in to proxy" than "actor accessed content"

and in that case should it be similar to the logged in VLE statements

**Comment by gmoger-jisc** [comment]
Can we say the student (actor) accessed this content (object), with the context being the authentication platform?

I think we do need to keep the actor as student.

Gareth Moger
Learning Analytics - Data Integration
Jisc

________________________________

**Comment by gmoger-jisc** [comment]
Yes, maybe then student logged in to auth platform with context being the host they were trying to reach.

Will have a think about this one.

Gareth Moger
Learning Analytics - Data Integration
Jisc

________________________________

**Comment by ds10** [comment]
> Can we say the student (actor) accessed this content (object), with the context being the authentication platform?

Yes, this is how it is at present (as I understand it, he authentication platform is context.platform)

> Yes, maybe then student logged in to auth platform with context being the host they were trying to reach.

Yes, it isn't like this at present, but it could be like the logged in vle statements if that is what we are describing.

**Comment by gmoger-jisc** [comment]
I think the first is better so that we can distinguish between accessing resources (though this requires authentication) and specifically logging in to a system.

Can we also add IP address to the recipe?

**Comment by ds10** [comment]
This thread has become quite long, so I am not sure what we mean by first one anymore, the student (actor) accessed (verb) resource (object)?

I've added IP address to context.extensions in 1.0.2:

The new [accessed ](https://github.com/jiscdev/xapi/blob/1.0.2/recipes/library/uxapi/library-accessed-econtent-template.json )statement now looks quite like the previous [viewed statement](https://github.com/jiscdev/xapi/blob/1.0.2/recipes/library/uxapi/library-viewed-econtent-template.json)

The differences in accessed statement:

- accessed verb instead of viewed verb
- no object.definition.extensions.subType
- no context.extensions.sessionId

**Comment by gmoger-jisc** [comment]
If the object is the resource being accessed (which I think is what we need) should the ID simply be the host name?

**Comment by ds10** [comment]
I'm not sure that sounds right? I'm guessing the hostname would then be the same for lots of different resources that share the same host then?

**Comment by gmoger-jisc** [comment]
Yes but we are not capturing the detail of those resources, only that they have accessed the host so what else would be used for the ID?  There is the full URL they have authenticated to, so maybe that is best as the ID.

**Comment by ds10** [comment]
I'm not sure what we should do if we don't know what the resource is they accessed. Would be worth revisiting this with the group.  I don't have the data and I am not on the analyst side either, so would really like input. But my thoughts:

a) we stick with _the student (actor) accessed (verb) resource (object)_ and use the full url

or 

b) rethink how the two statements relate so that:
ii) Where we have data that that've accessed a system but not sure what the resource  is: a student (actor) accessed (verb) the proxy (object) (or some kind of authenticated or logged in statement)
iii) where we do know the resource:  _the student (actor) viewed (verb) resource (object)_

**Comment by ds10** [comment]
Summary for 3rd December call.

**I think this is the most important ticket and would like to start and concentrate on this one**

Currently in 1.0.2, we have two content statements 1 for viewing and 1 for accessing, they overlap, the only difference being slightly less required in the accessing statement.

Some questions:

1. What is the purpose of each statement. 
1b. From the data that jisc have, can we tell the difference between viewed and accessed, or are all statements actually accessed?
1c. For the access statement: What are they are accessing? Is it individual bits of content (that we have an identifier for) or is it just a host with unknown function (but we may have a url we can stick in an extension)
1d. Is an authenticate statement (similar to the VLE one) still required?
1e. What analysis will take place on these statements?

**Comment by ds10** [comment]
from call: 
- two statements:
1. viewed to stay as is
2. accessed to be smilar but:
- object will be domain
- full url string in extension
- be clear about what plaform in documention

**Comment by ds10** [comment]
I've made a commit to what I think we agreed in the call.  I think the question is, what is the object in the accessed statement. It isn't really a resource anymore, we may not know what it is?

So I think it is something along the lines of:

_the student_ (actor) _accessed_ (verb) _service_ (object)

I've removed the hostname extension because the hostname is now the id of the object, and a full-url extension captures the full string. Thoughts?

```
	"object": {
		"objectType": "Activity",
		"id": "http://onlinelibrary.jisc.ac.uk/",
		"definition": {
			"type": "http://activitystrea.ms/schema/1.0/service",
			 "extensions": {
				"http://xapi.jisc.ac.uk/full-url": "http://onlinelibrary.jisc.ac.uk/doi/10.1111"
			}
		}
```

**Comment by gmoger-jisc** [comment]
The host name would be things such as 'glos.on.worldcat.org'.  Would this be an acceptable format as a IRI?

I'm still undecided on the full URL.  I think this is going to be difficult to include in some cases, usually when they are including search terms.  I'm not sure what additional value it provides but maybe I am missing something.

**Comment by ds10** [comment]
is the question asking: 

Is using the hostname in the object.definition.type acceptable? 

The way I had thought about this was similar to the VLE viewed statements, in these statements the id of the item being viewed is the irl of the activity, for example in the viewed resource example the id is: http://moodle.data.alpha.jisc.ac.uk/mod/page/view.php?id=9

This was decided before Cetis was invovled, so I wasn't part of the discussion but I always thought it was ok because the spec says:

- An Activity id MAY point to metadata or the IRL for the Activity.

So, I had thought that if we were saying actor is accessing a service, then I had thought that the hostname was doing something *similar* but now you've given me doubt. I think it fits in with the specs 'musts', but not its shoulds'

- An Activity id MUST be unique.
- An Activity id MUST always reference the same Activity.
- An Activity id SHOULD use a domain that the creator is authorized to use for this purpose.
- An Activity id SHOULD be created according to a scheme that makes sure all Activity ids within that domain remain unique.

Would like to hear opinions @arc12 @alanepaull @ryansmith94

**Comment by gmoger-jisc** [comment]
The data is quite a mixed bag of direct links and search queries.  However the direct links themselves can be quite verbose e.g.

> http://www.sciencedirect.com/science/link?ref_val_fmt=info:ofi/fmt:kev:mtx:journal&svc_val_fmt=info:ofi/fmt:kev:mtx:sch_srv&rfr_dat=saltver:1&rfr_dat=origin:ONECATE&ctx_enc=info:ofi/enc:UTF-8&ctx_ver=Z39.88-2004&rft.issn=14715953&rft.volume=14&rft.issue=2&rft.spage=106&rfr_dat=md5:eb47deec229f903e4ce3533aef9e4202

For the purpose of this recipe I think it is enough for us to say that a user accessed this service (the host).

**Comment by alanepaull** [comment]
+1 to this approach from me.

Caveats:

- I think that the full-url extension is not necessary at this stage; especially if we cannot see a use for it currently. It would be relatively easy to add it later if we define a need.

- With the ID, are we risking identifying a non-unique Activity? For example, you might conceive of a domain with ID "http://www.poppleton.ac.uk" that is used for "Jane Doe accesses Poppleton's eContent store". Then, somewhere else we have statements with this ID but for a different Activity not related to Library eContent stuff. This circumstance would mean that analysis using this ID would be wrong. However, I may be worrying about a non-existent problem. Could some of our analyst friends reassure me, @arc12 ?

**Comment by arc12** [comment]
Re Alan's second caveat/concern: maybe a resolution/mitigation would be to use a more specific object.definition.type. This is AFAIK indexed in the LDH, so queries should perform OK. So we just query for econtent service if we wish to exclude other stuff with same nominal activity object id.

**Comment by gmoger-jisc** [comment]
I have been testing some statements with the ID this morning and this will not work as an IRI (The LDH rejects it):
**openurl.ebscohost.com**

However this will:
**https://openurl.ebscohost.com/**

**Comment by ds10** [comment]
Alan's caveat and Adam's mitigation:

If we use a more specific object.definition.type and query by that tyoe to avoid other activities with same id, aren't we just breaking the spec:

•An Activity id MUST be unique.

Because we then have different activities with the same id?

**Comment by gmoger-jisc** [comment]
Can I purpose we keep the activity type as "..service", don't capture the URL and use the hostname as object id (including the protocol, http/https)?

If we need to review it later then so be it but these are the main data points we need from the data and I am keen to get this released as soon as possible.  I don't think we have highlighted any show-stopping concerns in this long thread and so the proposal above seems like a relatively safe

**Comment by ds10** [comment]
I think the only concern is with hostname that the activity id's may not be unique if they are reused for a different activity type.

@gmoger-jisc unless anybody shouts our object would then look like this:

```
	"object": {
		"objectType": "Activity",
		"id": "http://onlinelibrary.jisc.ac.uk/",
		"definition": {
			"type": "http://activitystrea.ms/schema/1.0/service"
		}
```

and I'll make the changes tomorrow, along with the rest of the 1.0.2 tickets, ready for review and merge into master and 1.1 early next week?

**Comment by gmoger-jisc** [comment]
sounds good.

**Comment by ds10** [comment]
Updated all the related files for accessed. Example:

``` javascript
{
	"version": "1.0.0",
	"actor": {
		"objectType": "Agent",
		"account": {
			"name": "Jsmith12",
			"homePage": "http://homepage.jisc.ac.uk"
		}
	},

	"timestamp": "2015-09-18T01:54:51.484Z",

	"verb": {
        	"id": "http://activitystrea.ms/schema/1.0/access"	,
       		 "display": {
            "en": "access"
        }
    },}
	},
	"object": {
		"objectType": "Activity",
		"id": "http://onlinelibrary.jisc.ac.uk/",
		"definition": {
			"type": "http://activitystrea.ms/schema/1.0/service"
		}

	},	
	"context": {
		"platform": "ezproxy",
		"extensions": {
			"http://xapi.jisc.ac.uk/version": "1.0.2",
			"http://id.tincanapi.com/extensions/ip-address": "165.154.154.1",
			"https://xapi.jisc.ac.uk/statementCat": "Library"
		}
	}
}
```
