### ISSUE TITLE
Platform missing from attendance recipe

### ISSUE THREAD

**Issue by alleycat58uk** [jiscdev/xapi#279]
There is no platform definition for the [attendance](https://github.com/jiscdev/xapi/blob/master/recipes/attendance/attendance.md) recipe

This is defined in other recipes as `statement.context.platform` for example the [studyapps](https://github.com/jiscdev/xapi/blob/master/recipes/studyapps/mobile-app.md#context) recipe

We are currently using the Jisc data explorer / study goal app for attendance and it would be useful to record this information

**Comment by gmoger-jisc** [comment]
Makes sense to me.  One to discuss for revised recipe.

**Comment by ds10** [comment]
This isn't consistant either. it looks like this is the Jisc JSON template, but not in the TSV or md description.

I'm guessing that this should be an optional property.

**Comment by ds10** [comment]
For Dec 3rd call:

This is in the Jisc JSON but not in the tsv or markdown, I think this made it in to the JSON template by accident.

@alleycat58uk is sugguesting that platform should be included because of institutions using studygoal etc?

Questions:
1. Should this be in the spec, required or optional
2. Is the platform that records the attendance (if that is what studygoal does) be the context.platform, description is:
_"Platform used in the experience of this learning activity. "_

**Comment by ds10** [comment]
platform added to 1.0.2 attendance md, text to be checked

**Comment by alanepaull** [comment]
See pull request for suggestions for changed description of context.platform: https://github.com/jiscdev/xapi/pull/283
I've also re-jigged examples and corrected the odd typo here and there.
