### ISSUE TITLE
Platform missing from Library item borrowed recipe

### ISSUE THREAD

**Issue by alleycat58uk** [jiscdev/xapi#280]
There is no platform definition for the [library-item-borrowing](https://github.com/jiscdev/xapi/blob/master/recipes/library/library-item-borrowing.md) recipe

This is defined in other recipes as `statement.context.platform` for example the [VLE Forum](https://github.com/jiscdev/xapi/blob/master/recipes/vle/forum.md#context) recipe

**Comment by ds10** [comment]
Again this is inconsistant, it is in the Jisc template, but not the markdown or TSV, like #279

**Comment by ds10** [comment]
For Dec 3rd call:

This is in the jisc template, but has never been part of the spec, My guess this has made it in to the JSON by error.

Questions:

1. Should this be in the spec? What is a library platform,?

**Comment by alleycat58uk** [comment]
> Should this be in the spec?

I think it is important, more so than for the VLE recipes which specify platform.  An institution will probably only run one VLE (ie Moodle, Blackboard) however the Library recipes may come from a number of different platforms

For querying purposes, platform would allow specific types of data to be pulled rather than all Library records as defined by statement category.


> What is a library platform?

This would be the system generating/supplying the data:
- Name of LMS (WorldShore, Primo etc)
- Discovery platform (EDS, EZProxy etc)
- Reading Lists (Talis, Rebus LORLS etc)


There is also a general point of consistency with these types of fields, something that is important to a developer using the data via the API.

**Comment by ds10** [comment]
@alleycat58uk thanks paul, 

Sorry, I am not well up on he library systems, what kinds of platforms would we see in library borrowing statements?

**Comment by alleycat58uk** [comment]
For the borrowing recipe it would be the name of the Library Management System (LMS) ie "WorldShare", "Primo" etc

**Comment by ds10** [comment]
from call:

- platform to be added to all docs
- double check platform definition through all documentation

**Comment by ds10** [comment]
platform added to all borrowed docs, wording on platform to be double checked

**Comment by ds10** [comment]
I'm just double checking this before I change the examples and close it ready for 1.0.2.

In previous versions of library statements that were merged from the jisc library repo (in viewed statements) the platform was hardcoded as "UxAPI". In fact, the viewed and access statements still have uxapi in their context.platform in the md example. I was just about to change these examples to have an institutional system, but want to make sure that is righ,

It seems we had already decided in these statements that context.platform was in the JSON and not in the description or TSV in ticket #237.

That ticket says

"JSON templates now require a PLATFORM but it is not in the TSV definition since it is supllied elsewhere"

In this ticket we have pretty much decided the same, except that we are now going to an example in the description file too. But I am not sure what Jisc mean when they say it is supllied from elsewhere.

So, what I am getting at... is doubling checking what is expected in context.platform.

Paul says it is:

> This would be the system generating/supplying the data:

Which I think we agreed on the call. But, previously Jisc have put "uxapi" in here. And as I understand it, this system doesn't supply the data, but transforms it from TSV to JSON.

I'm guessing that Michael/Lee used to put "uxapi" in context.platform for library statements, but what we are actually after is the institutional system generating the data.

BUT we are not recording what the platform is in the TSV. So, is jisc still pulling  this in from elsewhere  else other than the TSV? Or is it not supplied because Jisc are expecting to put "uXAPI" in there.

This also applies to the attendance context.platform

**Comment by alanepaull** [comment]
My understanding is the same as David's. We should be picking up context.platform from elsewhere - system-generated when file is created or imported. Could Gareth confirm?

**Comment by gmoger-jisc** [comment]
Yes we should be recording this for each institution and adding it to the statements during processing of the TSV files.  The platform should not be "UxAPI" (which is the TSV translator and ingestion process) as this is recorded in the client details on load to the LDH.

**Comment by ds10** [comment]
Sorry, just to clarify

When you say recording it for each institution, you mean seperatly from the TSV provided. So, the platform is recorded in some client details config, which is seperate part of the process that feeds the template. 

i.e platform is not required in the TSV itself

**Comment by gmoger-jisc** [comment]
Yes that's right.
