### ISSUE TITLE
devicelocation format

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/xapi#297]
Please see device location in attendance context fields:
https://github.com/jiscdev/xapi/blob/master/recipes/attendance/attendance.md#context

Currently: **context.extensions.https://xapi.jisc.ac.uk/devicelocation**

Should it be camel case in line with others: **context.extensions.https://xapi.jisc.ac.uk/deviceLocation**

I am not sure it matters since there are other files named inconsistently also e.g. context.extensions.https://xapi.jisc.ac.uk/captured_from

**Comment by ds10** [comment]
Agreed that there are inconsistancys, this is accumulation from accumulation of approaches and contributers and one of the reasons that library recipes etc was brought into this repository.

Can we discuss the inconsitencies at the next call:

- Url structure going forward
- underscore, camel case going forward
- is there a long term goal we should be headed towards (w3id/purl resolvable iri's sameAS jisc iris)?

**Comment by ds10** [comment]
Todo:

- come up with a consistent iri scheme
- really dont worry about long term w3id and resolvable iris. But think about it to help you sleep

**Comment by ds10** [comment]
it is fine to change devicelocation because it isn't being used

**Comment by ds10** [comment]
deviceLocation seemed to be inconsistent in the spec, now deviceLocation

**Comment by ds10** [comment]
For discussion at 1 April:

- deviceLocation was inconistent anyway, it is now deviceLocation across spec
- Propose that going forward we use delimiter seperated instead of letter case. Sugguest snake_case.
- Currently minted iris are either follow the structure xapi.jisc.ac.uk/<term> or xapi.jisc.ac.uk/<recipe>/<term>. Propose that going forward we go with a convention that indicates the property instead because they can be used across recipes. For example xapi.jisc.ac.uk/verbs/<verb> xapi.jisc.ac.uk/extensions/<extension>
- Will document this in the spec

**Comment by ds10** [comment]
From 1 april call:

* Fine with sugguested convention going forward
