### ISSUE TITLE
Library borrowed items - use cases

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/xapi#331]
We have collected feedback from our institutions providing library data for borrowed items.  For our use case with learning analytics we have determined it not appropriate to capture the individual content title and identifiers.  As we cannot link the content to the students course we are unable to filter out content that might have been borrowed for personal use.  We are instead pursuing engagement with reading lists, for library and other content based activities, as these are intrinsically linked to modules/courses.

We don't want to change the existing recipe as it has use cases outside of learning analytics however for our purposes we will not collect ITEM_ID, ITEM_NAME and OCLC_NUMBER from institutions.  As such we need to determine what is best placed in the object.id and object.name fields as these are required for xAPI validation.  

Does anyone have a view on this?

Secondly do we need to capture field requirements somewhere which are specific to our implementations?  That might have be something we host somewhere else.

**Comment by ds10** [comment]
I need to think about this, but would the current template still work?

The activity id is constructed like so: **HOMEPAGE**/library/**ITEM_ID**",

as it is, the without the activity id it would just be  **HOMEPAGE**/library

so, is it suffucent for the activity to be *something from that library*, keeping the type:  as http://xapi.jisc.ac.uk/library/resource

[From Brian Miller:](https://xapi.com/blog/deep-dive-activity/):

> For instance, if we want to be able to track attendance at a conference, it may be sufficient to create an activity for the conference as a whole. But, if we want to know the most popular speaker at a conference, we will need to have at least session granularity to our data

I haven't had long to think about it, but I see the **ITEM_ID** as being the granuarity we may or may not have.

Not sure I get this second question:

> Secondly do we need to capture field requirements somewhere which are specific to our implementations? That might have be something we host somewhere else.

**Comment by gmoger-jisc** [comment]
Yes I think the current template should stay in place but we will have to omit certain fields from our collection and processing.

I take the point on the activity id.  I think will this just need to be library/resource as you say.

On the second question, what I am asking is do we document this within the repository here or somewhere else?  For example, as a note in the input definitions:

> For Jisc's Learning Analytics implementation the following fields are not required ...

**Comment by ds10** [comment]
OK, so these specs are being used internally in Jisc for different things? And this is leading to a situation where some collected fields are required for Jisc LA, but not for other implementations? 

Thinking out loud a bit here:

I guess I've always thought as statement templates/common structures/vocab being gospel spec, but the input definitions and template being written to support Jisc LA operations (but what I've thought hasn't mattered, because they go hand in hand).

So, the different implementations mean that the spec won't change (because object.id is still required) but the 'support files' would (because different projects require different inputs)?

I guess it depends, we already brought the input definitions in to this repository from another, the reasoning was that it was easier to manage. If there are just a few notes to put in then it might be best just doing what you sugguest. On the other hand, if there are going to be lots of implementations with different requirements then it might be best to move the 'support files' out of the spec and have different repositories for different implemenations.

**Comment by gmoger-jisc** [comment]
No, they are only being used for LA right now but I am trying to think to the future.  I guess at that point different services might need their own repository of recipes and that is where the input and differences would be captured rather than "polluting" this space.

As such if we accept that the input definitions are there for Jisc LA only then they should be changed to reflect what I have outlined above.

**Comment by ds10** [comment]
from call

- make it clear what is and what isn't required by LA in the input definitions
- revist activtiy id, we think we are fine, but check

**Comment by ds10** [comment]
I said I would spend some time with this on the call, revisiting I am not happy with this statement and would like to talk it through.

I have some questions/comments:

* Firstly, Is this statement currently in use, inparticular I'm wondering if the http://xapi.jisc.ac.uk/library/resource iri is used? This was minted before the consistancy guidelines and should be http://xapi.jisc.ac.uk/activity/resource. I think the term library is confusing in the iri because we are using it here to say 'this activity type belongs to library recipes', but we are working away from that older structure of iris.  Furthermore, We don't actually seem to have a definition for the http://xapi.jisc.ac.uk/library/resource activity type in the Vocab, which isn't helpful. The question of what is the activity type needs sorting out.

* What was sugguested on the call was that we just don't need to worry about not having an item id, as the activity id would just become HOMEPAGE/library instead of HOMEPAGE/library/ITEMID. In that case the activity id identifies the resource borrowed from, rather than an individual resource. But, then the activity type would need to identify if it was a resource collection or a resource?

* The Natural language example of a typical borrowed statement Statement: "The student, John Smith, borrowed the book 'Introduction to Java' (OCLC number 1234567890) from the university library at 13:05 on 18 November 2018.", which is not what we are describing if we don't have an item id

I guess what I am saying is that a recipe for "Library borrowed items" becomes difficult when we don't know the items, without the ID it becomes "borrowed from".  So, is what I was sugguesting (that without an item id we are just saying we are borrowing from a collection of resource) too much of a stretch for one statement? 

Would like thoughts on this one @arc12 @alanepaull

**Comment by alleycat58uk** [comment]
It might be worth noting that Talis reading lists are being explored and, whilst you cannot link a particular borrowed item to the 'students course' you will be able to say that an item from the students reading list has been borrowed.

This extends further to copyright cleared articles (scanned or provided by Cilip DCS) which Talis also ties to the module.

**Comment by gmoger-jisc** [comment]
We are using this activity type:
http://xapi.jisc.ac.uk/library/resource
Happy to use the new form when we amend the data we have.

Not sure on the second point but I think it's enough to say the are borrowing a resource (rather than from a collection).

Natural language should be updated to reflect these changes.

I'm not sure a new statement is necessary, we just need to get this right from the perspective of 'borrowed resource from library' without being specific as to the resource.  I am happy with the statement as it is an just exclude the data points that we will no longer capture.

**Comment by alanepaull** [comment]
As a result of discussions @ds10 and I had earlier today, I think we may be looking at 2 subtly different use cases, and therefore 2 different statement templates here. One is 'student borrowed item x from library y', where the primary activity is the student borrowing a specific item, and the library is in the context. The other is 'student borrowed something from library y', where the primary activity is borrowing from the library and the item is itself is unknown and / or not directly of interest.

Natural language versions might be these (drawn from the current template):

First: "The student, John Smith, borrowed the book 'Introduction to Java' (OCLC number 1234567890) from the university library at 13:05 on 18 November 2018."

Second: "The student, John Smith, borrowed something from the university library at 13:05 on 18 November 2018."

These natural language versions suggest 2 conceptually different statements, one with a verb "borrowed" and an object of the specific item, and the other with a verb "borrowed_from" and an object of the library.

The 2 different statements might look like this:

First, from the current statement template:
``` javascript
{
	"actor": {
		"objectType": "Agent",
		"name": "John Smith",
		"account": {
			"name": "jsmith20",
			"homePage": "http://library.universityofjisc.ac.uk/" 
		}
	},
	"verb": {
		"id": "http://activitystrea.ms/schema/1.0/borrowed",
		"display": {
			"en": "borrowed"
		}
	},
	"object": {
		"objectType": "Activity",
		"id": "http://library.universityofjisc.ac.uk/13579",
		"definition": {
			"type": "http://xapi.jisc.ac.uk/library/resource",
			"name": { "en": 
				"Introduction to Java"
			}
		},
		"extensions": {
			"http://xapi.jisc.ac.uk/subType": "http://id.tincanapi.com/activitytype/book",
			"http://oclc.com/number": "1234567890",
			"http://xapi.jisc.ac.uk/subject_area": "Computing"
      		}
	},
	"timestamp": "2018-11-18T13:05:51.484Z",
	"context": {
		"platform" :"WorldShare",
		"extensions": {
			"http://xapi.jisc.ac.uk/version": "1.1",
			"http://xapi.jisc.ac.uk/recipeCat": "Library",
			"http://xapi.jisc.ac.uk/borrowing_site": "Main Library"	
		}
	}
}
```
Second, new-minted:
``` javascript
{
	"actor": {
		"objectType": "Agent",
		"name": "John Smith",
		"account": {
			"name": "jsmith20",
			"homePage": "http://library.universityofjisc.ac.uk/" 
		}
	},
	"verb": {
		"id": "http://xapi.jisc.ac.uk/borrowed_from",
		"display": {
			"en": "borrowed from"
		}
	},
	"object": {
		"objectType": "Activity",
		"id": "http://library.universityofjisc.ac.uk/mainLibrary",
		"definition": {
			"type": "http://xapi.jisc.ac.uk/borrowing_site",
			"name": { "en": 
				"Main Library"
			}
		},
	},
	"timestamp": "2018-11-18T13:05:51.484Z",
	"context": {
		"platform" :"WorldShare",
		"extensions": {
			"http://xapi.jisc.ac.uk/version": "1.1",
			"http://xapi.jisc.ac.uk/recipeCat": "Library"
		}
	}
}
```

What do we think? Is there any difficulty with having 2 statement templates? It may be that for the learning analytics service, only the 'borrowed_from' would be used, at least for now, as it has proven difficult to get the details of real items borrowed.

We would like to get the views particularly of @arc12, as well as those already involved in this discussion.

**Comment by arc12** [comment]
:-) I was just thinking of responding when I saw you had "@'ed" me

This is an interesting question. I think it boils down to asking what the best/conventional/... pattern is for making xAPI statements where the "object" is a class, or an abstract thing. [I think we should be careful overloading these terms with the meanings which OO-thinking has created]

Adam borrowed War and Peace from Buxton Library
Adam borrowed a book from Buxton Library
Adam borrowed something from Buxton Library
Adam borrowed War and Peace from a public library

At first glance, it feels inelegant to use a separate statement template for these. On the other hand, it feels horrible to mix up real object identifiers with object type identifiers in object.id

I'd like to suggest a way of using the 2nd example with an added decoration for the identify of the book, to deal with the use case of the first example.... but I cant!

Its not like we can just omit "object", can we? object is required, I think. So we cant say something like "Adam spontaneously combusted" in xAPI.

So... it looks like 2 templates.

**Comment by ds10** [comment]
I agree with it looking like 2 templates, I can see scenarios where it looks like a user borrowed a library while another user was in it

For discussion I've added the new template to 1.1.1 and linked from the readme page.

[Md page](https://github.com/jiscdev/xapi/blob/1.1.1/recipes/library/library-location-borrowing.md)

[definitions](https://github.com/jiscdev/xapi/blob/1.1.1/recipes/library/uxapi/library-location-borrowed-input.md)

[template](https://github.com/jiscdev/xapi/blob/1.1.1/recipes/library/library-location-borrowing.md)

**Comment by gmoger-jisc** [comment]
Do we really need a verb change here?  Can we not simply say that they have borrowed and the object ID is resouce:
"id": "http://library.universityofjisc.ac.uk/resource",

This suggests they have borrowed a resource from the library without specifying the resource itself.

`{
  "actor": {
    "objectType": "Agent",
    "name": "John Smith",
    "account": {
      "name": "jsmith20",
      "homePage": "http://library.universityofjisc.ac.uk/" 
    }
  },
  "verb": {
    "id": "http://xapi.jisc.ac.uk/borrowed",
    "display": {
      "en": "borrowed from"
    }
  },
  "object": {
    "objectType": "Activity",
    "id": "http://library.universityofjisc.ac.uk/resource",
    "definition": {
      "type": "http://xapi.jisc.ac.uk/resource",
      "name": { "en": 
        "resource"
      }
    },
  },
  "timestamp": "2018-11-18T13:05:51.484Z",
  "context": {
    "platform" :"WorldShare",
    "extensions": {
      "http://xapi.jisc.ac.uk/version": "1.1",
      "http://xapi.jisc.ac.uk/recipeCat": "Library"
    }
  }
}`

**Comment by ds10** [comment]
I'd like to talk about this at the call, there are a lot of issues and it is hard to track them all.

1. The first issue is about knowing the resource vs not knowing it.

I agree to what you are sugguesting some extent, whenever I open this ticket I think it is the most elegant way to do it, and is along the lines of what I first sugguested, I think the reason that we've danced around that is because the object.id id must always reference the same Activity.

I get what your are saying, because I am back and forwards on this myself. If we knew the item we could use the activity.id as such:

_http://library.universityofjisc.ac.uk/resource/#id_

and if we don't have an id then we just dont then we just use

_http://library.universityofjisc.ac.uk/resource/_

which suggests they have borrowed a resource from the library without specifying the resource itself.

But this is when I find it tricky, because if we have two different books and we know their IDs then we DO have two seperate activity IDs: _http://library.universityofjisc.ac.uk/resource/1 & _http://library.universityofjisc.ac.uk/resource/2_ , if we dont have the id then we just say 'its a resource - we dont know what', and they both use the same id: _http://library.universityofjisc.ac.uk/resource/_ . So suddenly that iri structure no longer references the same activity unless we have subtlety changed what the object.definition.type means?

I guess I'm not sure where I stand on this one and would like us all to be very clear.

2. Things get even more confusing when you want to track an item that may be avalible at more than one library. So with the current way the iri structure works we are saying "borrowed recouse X from library Y" ( e.g http://library.universityofjisc.ac.uk/resource/45), but we are mixing two types of things in one URI. We might want to track a book's popularity across libraries? you couldnt just look up the identifier for the book, because they are always tied to a library,

**Comment by gmoger-jisc** [comment]
I would think that the activity.id would always be there same, no?  We're talking about borrowing a resource even if we don't know what that resource is, and so it should be:
**http://xapi.jisc.ac.uk/library/resource**

Or are we getting confused with the object.id?

> If we knew the item we could use the activity.id as such:
> 
> **http://library.universityofjisc.ac.uk/resource/#id**
> 
> and if we don't have an id then we just dont then we just use
> 
> **http://library.universityofjisc.ac.uk/resource/**
> 
> which suggests they have borrowed a resource from the library without specifying the resource itself.

I'm happy with this but looking for other views.

**Comment by arc12** [comment]
It is dissonant (to me, at least) to have statements of the form Actor borrowed X, with X being drawn from BOTH the set of identifiers for class of things AND the set of identifiers for the instance of things.

Incidentally, it might also be worth considering the implications of the OCLC work known as FRBR
https://www.oclc.org/research/activities/frbr.html
In the FRBR terminology, I think "manifestation" is the most likely level for identifying things borrowed.

**Comment by ds10** [comment]
On the call today;

* Gareths example is checked against current borrowed
* /resource to be added to the end of the uri
* no id identifies a resource collection, but **not** physical location
* Remove borrowed from
* mint http://xapi.jisc.ac.uk/library/resource

**Comment by ds10** [comment]
in 1.1.1

* item id no longer required
* /resource added to iri

**Comment by gmoger-jisc** [comment]
This is the template that I am now looking at:
`{
	"version": "1.0.0",
	"actor": {
		"objectType": "Agent",
		"account": {
			"name": "**USERNAME**",
			"homePage": "**HOMEPAGE**"
		}
	},
	"verb": {
		"id": "http://activitystrea.ms/schema/1.0/borrowed",
		"display": {
			"en": "borrowed"
		}
	},
	"object": {
		"objectType": "Activity",
		"id": "**HOMEPAGE**/library/resource",
		"definition": {
			"type": "http://xapi.jisc.ac.uk/library/resource",
			"name": {
				"en": "resource"
			},
		    	"extensions": {
			    	"http://xapi.jisc.ac.uk/subType": "**ITEM_SUBTYPE**",
					"http://xapi.jisc.ac.uk/subject_area": "**SUBJECT_AREA**"
		    	}
		}
	},

	"timestamp": "**TIMESTAMP**",

	"context": {
		"platform": "**PLATFORM**",
		"extensions": {
			"http://xapi.jisc.ac.uk/statementCat": "Library",
			"http://xapi.jisc.ac.uk/borrowing_site": "**BORROWING_SITE**",
			"http://xapi.jisc.ac.uk/version": "1.1.1"
		}
	}
}`

Does that match expectations?

**Comment by ds10** [comment]
that is more or less what is in the 1.1.1 brach except in the object:
```

	"object": {
		"objectType": "Activity",
		"id": "**HOMEPAGE**/resource/**ITEM_ID**",
		"definition": {
			"type": "http://xapi.jisc.ac.uk/library/resource",
			"name": {
				"en": "**ITEM_NAME**"
			},
		    	"extensions": {
			    	"http://xapi.jisc.ac.uk/subType": "**ITEM_SUBTYPE**",
					"http://xapi.jisc.ac.uk/subject_area": "**SUBJECT_AREA**",
					"http://oclc.com/number": "**OCLC_NUMBER**"
		    	}
		}
	},
```
The reason I have kept **ITEM_ID**", and **ITEM_NAME**" is because I thought removing them would be a breaking change and would move it to 1.2? We could change them to option/depricate them in 1.1.1 and remove them from templates?

I haven't removed the library visited template yet, but I think we decided it was only in the dev branch and could be removed when we were happy?

**Comment by gmoger-jisc** [comment]
It is not a breaking change for us, so happy for this to be released with 1.1.1.

**Comment by ds10** [comment]
Just to clarify, I'll make it optional and depricated, and remove it from the templates.

It will be removed in 1.2?

**Comment by gmoger-jisc** [comment]
Sorry David I'm confused.. make what deprecated?

The ITEM_NAME and OCLC_NUMBER should be optional but we need to be clear with our LA customers that they should not be sent with any extract.  Ideally I would like it removed from the spec altogether, in 1.1.

**Comment by ds10** [comment]
Right sorry, wasn't clear.

ITEM_NAME and OCLC are already optional in 1.1.

I think the only change for 1.1.1 is to make ITEM_ID optional (currently it is required).

I was under the impression that anything related to the item (ITEM_NAME, OCLC and ITEM_ID etc) was to be removed. This would be breaking and would have to go in 1.2? Which means deprecated in 1.1.1?

**Comment by gmoger-jisc** [comment]
Yes it should be optional and ultimately removed.  Why not remove it with 1.1 though?  We already set up to manage the change so not "breaking" for us.

**Comment by ds10** [comment]
1.1 was released in October: https://github.com/jiscdev/xapi/releases/tag/v1.1 so we would be changing the current release. So, I guess as the spec people (it is breaking in the spec) we can't really advise you go ahead and do anything other than hotfixes/documentation fixes to that version.

The only changes in 1.1.1 are the new faculty accessed statements and to make item_id optional, so I would rather make those changes in 1.1.1 and then release that version/merge that into master. Target setting would then be pushed back again to 1.1.2.

**Comment by gmoger-jisc** [comment]
yes that's fine - I'm getting mixed up between version numbers.
