### ISSUE TITLE
Amend fields for lecture capture

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/xapi#332]
This is in the latest branch but some fields are not necessary:

- EMAIL [0..1]
- SESSION_ID [1]
- CLIENT_IP [0..1]

Can they please be removed?

**Comment by ds10** [comment]
Sorry for the Christmas delay on this: 

Session_id and Client_IP are both optional as part of the common identifer [ContextA](https://github.com/jiscdev/xapi/blob/master/common_structures.md#contexta) used by the video capture recipe.

Two comments:

1:

I think a few times we've come to the agreement that if a property is optional then it belongs in the TSV definitions and example input just uncase. More recently however, we've discussed that the TSV definitions are confusing for users of the LA service when we have items in the those definitions that are not relevent to that, I think we spoke about making it a LA service TSV definition and sign posting it as such, thoughts?

2: Some of these are wrong anyway, Session_ID should be optional, and email is not required or optional as part of [Common entity identifier: ActorA](https://github.com/jiscdev/xapi/blob/master/common_structures.md#actora)

**Comment by gmoger-jisc** [comment]
Are you saying to have a separate TSV definitions for la-service?

**Comment by ds10** [comment]
No, I think that we should follow what we've always said and keep optional ones in the TSV, so email would go, session would be optional and client_ip would stay,

In ticket [331](https://github.com/jiscdev/xapi/issues/331) you sugguest putting:

> For Jisc's Learning Analytics implementation the following fields are not required .

So that would go next to client_ip and session_id. Further down from yout comment looks like that is what was agreed on that call

**Comment by gmoger-jisc** [comment]
OK that sounds fine.

**Comment by ds10** [comment]
just to check, the spec is correct on this one and the TSV and definitions are wrong. So this is a master branch hot fix.

**Comment by ds10** [comment]
Just looking through this to make the required changes and there is a documentation error, 

It says that this uses ContextA, but ContextA requires an IP address where as this doesn't. This is a documentation error.

Sugguested change based on this:
* remove the fields not required because it is not not a commen entity anyway
* change documentation to reference to take out reference to common identifer ContextA
