### ISSUE TITLE
Candidate Recipe: Authorise

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#82]
Taken from the [candidate vocab document](https://docs.google.com/spreadsheets/d/10xhtR9kjCSgmqk_6B4KprY4cvVUWXJctRVZaNf3lPZs/edit#gid=262364132). This ticket is for voting on where to place effort on candidate recipes (thumbs up/thumbs down).

Purpose: This activity would record authorisation being given to a person by a service.

Proposed verb: http://activitystrea.ms/schema/1.0/authorize

**Comment by arc12** [comment]
dont like:
- level of abstraction - excessive IMO to bracket room and file access
- "business transaction" and "billable" - not applicable to our context

**Comment by ds10** [comment]
hmm perhaps, I am putting too much thinking about them in the ticket at this stage, perhaps these should be votes for 'do we a similar this recipe/should effort go here' , rather than 'vote if you think the vocab is correct'

**Comment by arc12** [comment]
@ds10 - OK...
In that case, two broad responses on different angles:
1. prioritise according to the data sources available and for which there is likely to be some practical analytical use in the near-term to validate or feed back into the initial recipe. Avoid things which sound like a good idea but lack these practical aspects.
2. conceptualise the division of recipes in terms of student actions likely to be of interest for LA. This is a bit wooly but I'm trying to get at the idea of both describing and prioritising recipes in a way which is not oriented to IT systems and actions. In the current case, I'd prefer (subject to #1) to look at something like "access" to a room being a manifestation of behaviour rather than a record of "authorisation". I think this will affect how we scope the vocabularies as well as giving us a more grippy handle on relevance to LA.

Adam

**Comment by ds10** [comment]
@arc12 ok thanks,
* There is a candidate vocab library that appeared during the hackathon, I think this was done by a group led by Wilbert with Lee adding some library recipes after.  The voting exercise is an attempt to revisit it, get feedback on and prioritise them. So, your comment is good guide on how people could give feedback (if they have data-sources or a use case in the near-team)

*access and authorisation, I made a mistake when copying over from the candidate vocab document, where access and authorisation are two seperate entries (but I managed to mix them up!) 

The candidate vocab i am working with is here: https://docs.google.com/spreadsheets/d/10xhtR9kjCSgmqk_6B4KprY4cvVUWXJctRVZaNf3lPZs/edit#gid=84476236
