### ISSUE TITLE
Authorisation recipe verb

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#96]
The current draft [authorsation ](https://github.com/jiscdev/xapi/blob/ds10-recipedev/recipes/authorise-service.mdd)recipe uses the verb 'http://activitystrea.ms/schema/1.0/authorize' from activity streams . The [description ](http://activitystrea.ms/registry/verbs/)is:

Indicates that the actor has authorized the object. If a target is specified, it means that the authorization is specifically in regards to the target. For instance, a service can authorize a person to access a given application; in which case the actor is the service, the object is the person, and the target is the application. In contrast, a person can authorize a request; in which case the actor is the person and the object is the request and there might be no explicit target.'

I'd read this as actor(shibboleth?) authorises object (person) to target (application). But xAPI has no  target property in a statement ?

There is also a draft[ person requests authorisation](https://github.com/jiscdev/xapi/blob/ds10-recipedev/recipes/authorise-person.md) recipe, which I think would be fine?

Ideas on the verb + usage?

**Comment by arc12** [comment]
David, all -
(a quick quibble with the activity streams definition: a person does not authorize a request, but the fulfilment of that request. at least I think that is what they mean. otherwise its like "you have permission to ask for more gruel")

As a general point, I'm not enthusiastic about fairly abstract recipes. Encompassing both a person responding to a request and the Shibb scenario feels too abstract to me. And I think it rather invites an over-broad scope of potential application. Surely, at this level of abstraction, we can declare that VLEs are involved in authorising users to access certain course areas. Or that the security system authorises access to the computer lab.

I would rather see verbs which are quite concrete, and give a fairly clear indication of what was done (without needing to nuance this by taking account of the object type). That just makes life easier to process the data in a less byzantine process. This isn't to say that there isn't value in looking at the abstract level and saying "there is an authorisation pattern", which several recipes might adopt so that there is some consistency.

If the requirement is a recipe which allows resource access using UKAMF services then let's be specific to that. Maybe call it the "federated access recipe". I think that could bring some attributes into scope which an abstact recipe might neglect.

And if it is about access card and building security, a different recipe, with different attributes from facilities databases.

Adam
